import { defineProducts } from "./types";

const DGS = "Deposits protected up to €100,000 per depositor by the EU Deposit Guarantee Scheme.";

export const ACCOUNTS = defineProducts([
  {
    sku: "ACC-EVERY-001",
    name: "Everyday Current Account",
    navLabel: "Everyday Account",
    category: "Accounts",
    subcategory: "Everyday",
    productType: "Current Account",
    url: "/products/accounts/everyday-account",
    accent: "#0D9488",
    badge: "No monthly fee",
    segment: "personal",
    tier: "free",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free everyday current account with a debit card, instant payments, no FX fees on card spending and smart budgeting built in.",
    cardDescription:
      "Everything you need day to day — debit card, instant payments, budgeting and no fees, ever.",
    tagline: "The account that runs your everyday money — free, fast and fee-free abroad.",
    longDescription:
      "The Everyday Current Account is the heart of NexaBank. You get an IBAN in minutes, a contactless debit card with no FX fees on card payments, instant transfers to anyone, salary and bill management with spending categories, and a real-time view of everything in the app. There is no monthly fee and no minimum balance — it stays free whatever you do with it.",
    displayPrice: "€0/month",
    access: "Instant",
    perks: [
      "No monthly fee, no minimum balance",
      "Debit card with no FX fees on card payments",
      "Instant transfers, 24/7",
      "Spending categories and budgets",
      "Open in minutes with your ID",
    ],
    features: [
      "Contactless debit card with Apple Pay and Google Pay",
      "0% FX markup on card payments in 150+ currencies",
      "Instant SEPA transfers and payment requests",
      "Automatic spending categories, budgets and bill reminders",
      "Round-Up Savings Pots and salary sorter included",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Valid government-issued ID",
      "Proof of address",
      "One Everyday Current Account per person",
    ],
    faq: [
      {
        q: "Is it really free?",
        a: "Yes — no monthly fee, no minimum balance, no card fee. Optional services such as express card delivery are priced separately.",
      },
      {
        q: "How quickly can I open it?",
        a: "Most customers have an IBAN within ten minutes of scanning their ID in the app.",
      },
      {
        q: "Can I get my salary paid in?",
        a: "Yes — share your IBAN with your employer, and the salary sorter can split it into bills, savings and spending automatically.",
      },
    ],
    keywords: [
      "current account",
      "checking account",
      "everyday account",
      "bank account",
      "debit card",
      "free account",
      "no fees",
      "IBAN",
      "open an account",
      "salary account",
      "instant payments",
      "budgeting",
    ],
    feeSummary: "€0 monthly fee · 0% FX on card payments",
    regulatoryNote: DGS,
    personas: ["all"],
    goals: ["spend", "save"],
    relatedSkus: ["SAV-INST-001", "CARD-START-001", "CASH-REW-001"],
    liquidity: "instant",
    price: 0,
    fxFeePct: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 12480,
    popularityScore: 98,
  },
  {
    sku: "ACC-JOINT-001",
    name: "Joint Account",
    navLabel: "Joint Account",
    category: "Accounts",
    subcategory: "Joint",
    productType: "Joint Account",
    url: "/products/accounts/joint-account",
    accent: "#0F766E",
    badge: "Two cards, one account",
    segment: "personal",
    tier: "free",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free shared current account for couples and households — two debit cards, shared bills, split expenses and one clear view.",
    cardDescription:
      "Share bills and household spending with a partner — two cards, shared budgets, one clear view.",
    tagline: "Run the household together — one account, two cards, zero arguments.",
    longDescription:
      "The Joint Account gives two people one shared pot for rent, bills and family spending, each with their own debit card and app access. Set shared budgets, see who spent what, and move money between personal and joint accounts instantly. Both holders have equal rights, and either can add the account to a savings goal such as a house deposit or a family holiday.",
    displayPrice: "€0/month",
    access: "Instant",
    perks: [
      "Two debit cards, both fee-free abroad",
      "Shared budgets and bill tracking",
      "Split any expense in one tap",
      "Instant moves from personal accounts",
      "No monthly fee",
    ],
    features: [
      "Equal access for both account holders",
      "Two contactless debit cards with 0% FX markup",
      "Shared spending categories, budgets and bill calendar",
      "Split-the-bill and settle-up between holders",
      "Shared savings goals linked to Round-Up Pots",
    ],
    eligibility: [
      "Both holders aged 18 or over and EU resident",
      "Both holders hold or open an Everyday Current Account",
      "Valid ID and proof of address for both",
      "One Joint Account per pair of holders",
    ],
    faq: [
      {
        q: "Do both of us need to be NexaBank customers?",
        a: "Yes — each holder needs their own Everyday Current Account, which is free and takes minutes.",
      },
      {
        q: "What happens if we separate?",
        a: "Either holder can freeze the account; closing it requires both holders or a court instruction.",
      },
      {
        q: "Can we have a joint savings pot?",
        a: "Yes — create shared Round-Up Pots or a Notice Account from the joint account.",
      },
    ],
    keywords: [
      "joint account",
      "shared account",
      "couple account",
      "household bills",
      "split expenses",
      "married",
      "partner",
      "family budget",
      "shared finances",
      "rent and bills",
    ],
    feeSummary: "€0 monthly fee · 0% FX on card payments",
    regulatoryNote: DGS,
    personas: ["family"],
    goals: ["family", "spend", "save"],
    relatedSkus: ["SAV-NOT-001", "INS-LIFE-001", "ACC-KIDS-001"],
    liquidity: "instant",
    price: 0,
    fxFeePct: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 3120,
    popularityScore: 80,
  },
  {
    sku: "ACC-STU-001",
    name: "Student Account",
    navLabel: "Student Account",
    category: "Accounts",
    subcategory: "Student",
    productType: "Student Account",
    url: "/products/accounts/student-account",
    accent: "#14B8A6",
    badge: "Interest-free overdraft",
    segment: "personal",
    tier: "free",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free current account for students aged 18 to 25 with a €500 interest-free overdraft, no FX fees and student discounts built in.",
    cardDescription:
      "Free banking for students — a €500 interest-free overdraft, no fees abroad and discounts on the things you actually buy.",
    tagline: "Built for student life — free, flexible, and forgiving at the end of the month.",
    longDescription:
      "The Student Account is the Everyday Current Account tuned for studying: a €500 interest-free arranged overdraft for the tight weeks, no FX fees on the year abroad, and partner discounts on transport, food delivery and software. It stays a Student Account while you are enrolled and converts to an Everyday account with a graduate overdraft period when you finish.",
    displayPrice: "€0/month",
    access: "Instant",
    perks: [
      "€500 interest-free arranged overdraft",
      "No monthly fee",
      "0% FX fees for your year abroad",
      "Student discounts at partner brands",
      "Converts to a graduate account when you finish",
    ],
    features: [
      "€500 interest-free arranged overdraft from day one",
      "Contactless debit card with 0% FX markup",
      "Student partner discounts on transport, food and software",
      "Budgeting tools tuned to term-time and loan instalments",
      "Graduate transition with a further 12 months of free overdraft",
    ],
    eligibility: [
      "Aged 18 to 25",
      "Enrolled in an accredited university or institution",
      "EU resident with valid ID",
      "Proof of enrolment uploaded annually",
    ],
    faq: [
      {
        q: "Is the overdraft really interest-free?",
        a: "Yes, up to €500 while you are a student and for 12 months after you graduate.",
      },
      {
        q: "Can I use it abroad?",
        a: "Yes — no FX fees on card payments and two free ATM withdrawals a month anywhere in the world.",
      },
      {
        q: "What happens when I graduate?",
        a: "The account becomes an Everyday Current Account; the interest-free overdraft continues for 12 months.",
      },
    ],
    keywords: [
      "student account",
      "student bank account",
      "university",
      "overdraft",
      "interest-free overdraft",
      "student discounts",
      "erasmus",
      "year abroad",
      "first bank account",
      "freshers",
    ],
    feeSummary: "€0 monthly fee · €500 interest-free overdraft",
    regulatoryNote: DGS,
    personas: ["student"],
    goals: ["spend", "education", "build_credit"],
    relatedSkus: ["LOAN-STU-001", "CARD-START-001", "SAV-ROUND-001"],
    liquidity: "instant",
    price: 0,
    fxFeePct: 0,
    maxAmount: 500,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 2210,
    popularityScore: 75,
  },
  {
    sku: "ACC-KIDS-001",
    name: "NexaKids Account",
    shortName: "NexaKids",
    navLabel: "NexaKids (6–12)",
    category: "Accounts",
    subcategory: "Kids",
    productType: "Kids Account",
    url: "/products/accounts/nexakids-account",
    accent: "#0891B2",
    badge: "Ages 6–12",
    segment: "kids",
    tier: "free",
    launchedAt: "2026-08-01T00:00:00",
    description:
      "A free pocket-money account for children aged 6 to 12 with a parent-controlled debit card, chores and savings goals in a kid-friendly app.",
    cardDescription:
      "Pocket money made simple — a parent-controlled card, chores, goals and 2% interest in a kid-friendly app.",
    tagline: "Their first money lessons — with you in control of every setting.",
    longDescription:
      "NexaKids is a pocket-money account for children aged 6 to 12. Parents set the allowance, approve or block merchant categories, and see every payment in real time; children get a colourful card and their own app view with chores, savings goals and 2% interest to watch their balance grow. No fees, no overdraft, and the card only works where you allow it.",
    displayPrice: "€0/month",
    access: "Parent-controlled",
    perks: [
      "Parent-controlled debit card",
      "Scheduled pocket money and chore rewards",
      "Savings goals with 2% interest",
      "Block merchant categories instantly",
      "No fees, no overdraft",
    ],
    features: [
      "Debit card with parental spending limits and category blocks",
      "Automatic pocket money on the day you choose",
      "Chores and rewards the child completes in their app",
      "Savings goals earning 2.0% AER",
      "Real-time notifications to the parent for every payment",
    ],
    eligibility: [
      "Child aged 6 to 12",
      "Parent or legal guardian holds an active NexaBank current account",
      "Child's identity document provided at opening",
      "One NexaKids Account per child",
    ],
    faq: [
      {
        q: "Can my child spend online?",
        a: "Only if you enable it — online payments and specific merchant categories are switched on or off by the parent.",
      },
      {
        q: "Can grandparents send money?",
        a: "Yes, via a gift link that goes straight into the child's savings goal.",
      },
      {
        q: "What happens at 13?",
        a: "NexaKids upgrades to NexaTeen automatically, with more independence and the same parental oversight.",
      },
    ],
    keywords: [
      "kids account",
      "children's bank account",
      "pocket money",
      "kids debit card",
      "parental controls",
      "chores",
      "first bank account for kids",
      "allowance",
      "money lessons",
      "under 12",
    ],
    feeSummary: "€0 monthly fee · no overdraft",
    regulatoryNote: DGS,
    personas: ["kids_teens", "family"],
    goals: ["kids", "family", "save"],
    relatedSkus: ["SAV-JUN-001", "ACC-TEEN-001", "ACC-JOINT-001"],
    liquidity: "instant",
    price: 0,
    aer: 2,
    fxFeePct: 0,
    riskLevel: 1,
    minAge: 6,
    customerRating: 4.9,
    reviewCount: 640,
    popularityScore: 58,
  },
  {
    sku: "ACC-TEEN-001",
    name: "NexaTeen Account",
    shortName: "NexaTeen",
    navLabel: "NexaTeen (13–17)",
    category: "Accounts",
    subcategory: "Teens",
    productType: "Teen Account",
    url: "/products/accounts/nexateen-account",
    accent: "#0E7490",
    badge: "Ages 13–17",
    segment: "kids",
    tier: "free",
    launchedAt: "2026-08-01T00:00:00",
    description:
      "A free current account for teenagers aged 13 to 17 with their own debit card, budgeting tools and light-touch parental oversight.",
    cardDescription:
      "Real banking for teenagers — their own card and budgets, with parents kept in the loop.",
    tagline: "Independence with a safety net — banking that grows up with them.",
    longDescription:
      "NexaTeen gives 13-to-17-year-olds a real current account: a contactless debit card that works online and abroad, budgeting tools, savings goals and a pay-in IBAN for part-time job wages. Parents see spending, can set limits and top up instantly, but teens run the day-to-day themselves. At 18 it becomes a Student or Everyday account without changing the IBAN.",
    displayPrice: "€0/month",
    access: "Instant, parent oversight",
    perks: [
      "Own debit card, online and abroad",
      "Parents see spending and can set limits",
      "Budgets and savings goals",
      "IBAN for part-time job wages",
      "Keeps the same IBAN at 18",
    ],
    features: [
      "Contactless debit card with online payments and 0% FX markup",
      "Parental view with optional spending limits and instant top-ups",
      "Budgeting, savings goals and 1.5% AER on savings",
      "Salary pay-in for part-time work and apprenticeships",
      "Seamless upgrade to a Student or Everyday account at 18",
    ],
    eligibility: [
      "Teenager aged 13 to 17",
      "Parent or legal guardian holds an active NexaBank current account",
      "Teen's identity document provided at opening",
      "One NexaTeen Account per teenager",
    ],
    faq: [
      {
        q: "Can a teen shop online?",
        a: "Yes — online payments are on by default, with parent-set limits and no gambling or age-restricted merchants.",
      },
      {
        q: "Is there an overdraft?",
        a: "No. The card declines rather than going negative.",
      },
      {
        q: "Does the parent see everything?",
        a: "Parents see transactions and balances; the teen manages budgets and goals themselves.",
      },
    ],
    keywords: [
      "teen account",
      "teenager bank account",
      "youth account",
      "debit card for teens",
      "first job",
      "part-time wages",
      "parental oversight",
      "13 to 17",
      "under 18 banking",
      "independence",
    ],
    feeSummary: "€0 monthly fee · no overdraft",
    regulatoryNote: DGS,
    personas: ["kids_teens", "family"],
    goals: ["kids", "spend", "save"],
    relatedSkus: ["ACC-KIDS-001", "SAV-JUN-001", "ACC-STU-001"],
    liquidity: "instant",
    price: 0,
    aer: 1.5,
    fxFeePct: 0,
    riskLevel: 1,
    minAge: 13,
    customerRating: 4.8,
    reviewCount: 410,
    popularityScore: 54,
  },
]);
