import { defineProducts } from "./types";

const DGS = "Deposits protected up to €100,000 per depositor by the EU Deposit Guarantee Scheme.";
const CREDIT = "Business credit subject to status, trading history and affordability checks. Representative APR shown.";

export const BUSINESS = defineProducts([
  {
    sku: "BIZ-ACC-001",
    name: "Business Current Account",
    navLabel: "Business Account",
    category: "Business",
    subcategory: "Business Account",
    productType: "Business Account",
    url: "/products/business/business-current-account",
    accent: "#4F46E5",
    badge: "First 3 months free",
    segment: "business",
    tier: "standard",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A business current account for sole traders and companies at €9 a month — invoicing, expense cards for your team and accounting integrations included.",
    cardDescription:
      "Banking that runs your business — invoicing, team cards and accounting sync for €9 a month.",
    tagline: "Everything a growing business needs from its bank, in one account.",
    longDescription:
      "The Business Current Account is built for sole traders, freelancers and companies up to 50 people. Open in a day with your registration documents, issue expense cards to your team with per-person limits, send branded invoices and get paid by card or transfer, and sync every transaction to Xero, QuickBooks or Sage. VAT is set aside automatically into a separate pot so the quarterly bill never surprises you.",
    displayPrice: "€9/month",
    access: "Instant",
    perks: [
      "Open in one working day",
      "Team expense cards with individual limits",
      "Branded invoicing with card payment links",
      "Accounting sync with Xero, QuickBooks and Sage",
      "Automatic VAT set-aside pot",
    ],
    features: [
      "Multi-user access with roles and approval flows",
      "Unlimited team debit cards with per-card limits and receipts capture",
      "Invoicing, payment links and automatic reconciliation",
      "Two-way sync with Xero, QuickBooks and Sage",
      "Automatic VAT and tax set-aside pots",
    ],
    eligibility: [
      "Registered sole trader, partnership or limited company in the EU",
      "Directors and owners aged 18 or over with valid ID",
      "Company registration and proof of trading address",
      "Businesses in eligible sectors (no gambling, adult or crypto exchange)",
    ],
    faq: [
      {
        q: "Is there a free period?",
        a: "Yes — the first three months are free, then €9 a month with no per-transaction fees on SEPA payments.",
      },
      {
        q: "Can my accountant access the account?",
        a: "Yes — invite them with read-only or preparer access at no extra cost.",
      },
      {
        q: "How many cards can I issue?",
        a: "As many as you need. Each card has its own limit, category blocks and receipt capture.",
      },
    ],
    keywords: [
      "business account",
      "business bank account",
      "sole trader",
      "freelancer",
      "limited company",
      "SME banking",
      "invoicing",
      "expense cards",
      "accounting integration",
      "VAT",
      "startup bank account",
      "company account",
    ],
    feeSummary: "€9/month after 3 free months · free SEPA payments · 0.4% FX",
    regulatoryNote: DGS,
    personas: ["business"],
    goals: ["business_growth", "spend"],
    relatedSkus: ["BIZ-POS-001", "BIZ-SAV-001", "BIZ-FX-001"],
    liquidity: "instant",
    price: 108,
    monthlyFee: 9,
    fxFeePct: 0.4,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 1040,
    popularityScore: 69,
  },
  {
    sku: "BIZ-LOAN-001",
    name: "Business Growth Loan",
    navLabel: "Growth Loan",
    category: "Business",
    subcategory: "Business Loan",
    productType: "Business Loan",
    url: "/products/business/business-growth-loan",
    accent: "#4338CA",
    badge: "Decision in 48h",
    segment: "business",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "Unsecured business loans from €10,000 to €500,000 over up to 7 years from 6.5% APR, with a decision in 48 hours for existing customers.",
    cardDescription:
      "Fund equipment, hiring or expansion — €10,000 to €500,000 unsecured, decision in 48 hours.",
    tagline: "Capital for the next step — equipment, people, premises or stock.",
    longDescription:
      "The Business Growth Loan funds investment in your business without tying up personal assets. Borrow €10,000 to €500,000 unsecured over one to seven years at a fixed rate, with a decision in 48 hours for businesses banking with us and a dedicated business lending manager for larger amounts. Repayment holidays of up to three months are available for seasonal businesses.",
    displayPrice: "from 6.5% APR",
    perks: [
      "€10,000 to €500,000 unsecured",
      "Fixed rate, fixed monthly repayment",
      "Decision in 48 hours for existing customers",
      "Up to 3 months' repayment holiday",
      "No early repayment penalty",
    ],
    features: [
      "Unsecured lending — no personal guarantee below €100,000",
      "Fixed APR from 6.5% over 12 to 84 months",
      "Decision within 48 hours with open-banking data",
      "Seasonal repayment holidays of up to three months a year",
      "Dedicated business lending manager above €100,000",
    ],
    eligibility: [
      "Trading for at least 12 months",
      "Annual turnover of €50,000 or more",
      "Registered in the EU with an active Business Current Account",
      "No unsatisfied court judgements",
    ],
    faq: [
      {
        q: "Do I need to provide security?",
        a: "Not below €100,000. Above that we may ask for a director's guarantee depending on trading history.",
      },
      {
        q: "How fast can I get the funds?",
        a: "48 hours to decision and funds the next working day for existing customers; around a week for new customers.",
      },
      {
        q: "Can I repay early?",
        a: "Yes, in part or in full, with no penalty.",
      },
    ],
    keywords: [
      "business loan",
      "growth loan",
      "SME loan",
      "unsecured business finance",
      "working capital",
      "equipment finance",
      "expansion",
      "hire staff",
      "cash flow",
      "startup loan",
      "commercial loan",
    ],
    feeSummary: "1% arrangement fee · no early repayment penalty",
    regulatoryNote: CREDIT,
    personas: ["business"],
    goals: ["business_growth", "borrow"],
    relatedSkus: ["BIZ-ACC-001", "BIZ-SAV-001", "INS-INC-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 6.5,
    minAmount: 10000,
    maxAmount: 500000,
    minTermMonths: 12,
    termMonths: 84,
    riskLevel: 1,
    minAge: 18,
    minIncome: 50000,
    customerRating: 4.5,
    reviewCount: 287,
    popularityScore: 50,
  },
  {
    sku: "BIZ-SAV-001",
    name: "Business Savings Account",
    navLabel: "Business Savings",
    category: "Business",
    subcategory: "Business Savings",
    productType: "Business Savings",
    url: "/products/business/business-savings-account",
    accent: "#3730A3",
    badge: "35-day notice",
    segment: "business",
    tier: "standard",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A 3.2% AER 35-day notice savings account for company cash reserves, tax set-asides and surplus funds up to €2M.",
    cardDescription:
      "Earn 3.2% AER on cash reserves and tax set-asides with 35 days' notice — no fees, no minimum term.",
    tagline: "Put idle cash to work without locking it away.",
    longDescription:
      "The Business Savings Account earns 3.2% AER on money your business does not need this month — tax set-asides, reserves, retained profit. Give 35 days' notice to withdraw, move money from your Business Current Account in one tap, and give your accountant read access. Balances up to €2M are accepted and interest is paid monthly.",
    displayPrice: "3.2% AER",
    access: "35-day notice",
    perks: [
      "3.2% AER, paid monthly",
      "35 days' notice, no minimum term",
      "Balances up to €2M",
      "One-tap transfers from your business account",
      "No fees",
    ],
    features: [
      "3.2% AER variable rate, interest paid monthly",
      "35-day notice withdrawals with no penalty",
      "Automatic sweep of surplus balances above a threshold you set",
      "Separate pots for VAT, corporation tax and reserves",
      "Read access for your accountant",
    ],
    eligibility: [
      "Active NexaBank Business Current Account",
      "Registered sole trader, partnership or limited company in the EU",
      "Minimum opening deposit of €1,000",
      "Authorised signatories verified",
    ],
    faq: [
      {
        q: "Why 35 days' notice?",
        a: "It lets us pay a higher rate than instant access while keeping the money available inside one tax cycle.",
      },
      {
        q: "Is business cash protected?",
        a: "Yes — eligible business deposits are protected up to €100,000 under the Deposit Guarantee Scheme.",
      },
      {
        q: "Can the sweep run automatically?",
        a: "Yes — set a threshold on your current account and anything above it moves to savings each night.",
      },
    ],
    keywords: [
      "business savings",
      "company savings account",
      "cash reserves",
      "corporate treasury",
      "tax set aside",
      "surplus cash",
      "notice account for business",
      "retained profit",
      "business interest",
    ],
    feeSummary: "No fees · interest paid monthly",
    regulatoryNote: DGS,
    personas: ["business"],
    goals: ["save", "business_growth"],
    relatedSkus: ["BIZ-ACC-001", "BIZ-LOAN-001", "SAV-TERM-001"],
    rateType: "variable",
    liquidity: "notice",
    price: 0,
    aer: 3.2,
    minAmount: 1000,
    maxAmount: 2000000,
    noticeDays: 35,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 198,
    popularityScore: 46,
  },
  {
    sku: "BIZ-POS-001",
    name: "Card Terminals & Online Payments",
    navLabel: "Payments & Terminals",
    category: "Business",
    subcategory: "Payments",
    productType: "Merchant Services",
    url: "/products/business/card-terminals-online-payments",
    accent: "#6366F1",
    badge: "Next-day settlement",
    segment: "business",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "Accept card payments in store and online at a flat 1.2% per transaction with next-day settlement into your Business Current Account.",
    cardDescription:
      "Take payments anywhere — terminals, tap-to-phone and online checkout at a flat 1.2%, settled next day.",
    tagline: "Get paid in store, online and on the go — one flat rate, settled next day.",
    longDescription:
      "Card Terminals & Online Payments lets your business accept every major card and wallet: a countertop or portable terminal, tap-to-phone on any Android device, and a hosted online checkout or payment links. Everything costs a flat 1.2% per transaction with no monthly fee, and funds settle into your Business Current Account the next working day with automatic reconciliation.",
    displayPrice: "1.2% per transaction",
    access: "Next-day settlement",
    specs: [
      { label: "Fee", value: "1.2% per transaction" },
      { label: "Settlement", value: "Next working day" },
      { label: "Channels", value: "Terminal, tap-to-phone, online" },
    ],
    perks: [
      "Flat 1.2% per transaction, no monthly fee",
      "Next-working-day settlement",
      "Terminals, tap-to-phone and online checkout",
      "Apple Pay, Google Pay and all major cards",
      "Automatic reconciliation in your account",
    ],
    features: [
      "Countertop and portable terminals from €0 upfront",
      "Tap-to-phone acceptance on Android devices",
      "Hosted checkout, payment links and invoice payments",
      "Flat 1.2% pricing including all card types and wallets",
      "Next-working-day settlement with itemised reconciliation",
    ],
    eligibility: [
      "Active NexaBank Business Current Account",
      "Registered business in the EU in an eligible sector",
      "Physical or online point of sale",
      "Authorised signatory verified",
    ],
    faq: [
      {
        q: "Are there any hidden fees?",
        a: "No — 1.2% per transaction covers everything. Terminals are free on a 12-month plan or €149 to buy outright.",
      },
      {
        q: "When do I receive the money?",
        a: "The next working day, into your Business Current Account, with each payout itemised.",
      },
      {
        q: "Can I take payments without a terminal?",
        a: "Yes — tap-to-phone turns an Android phone into a terminal, and payment links work for remote sales.",
      },
    ],
    keywords: [
      "card terminal",
      "POS",
      "accept card payments",
      "merchant services",
      "online payments",
      "payment links",
      "tap to phone",
      "checkout",
      "contactless payments",
      "shop payments",
      "restaurant payments",
    ],
    feeSummary: "1.2% per transaction · no monthly fee",
    regulatoryNote: "Merchant services subject to acceptable-use policy and sector eligibility.",
    personas: ["business"],
    goals: ["business_growth", "spend"],
    relatedSkus: ["BIZ-ACC-001", "BIZ-FX-001", "BIZ-SAV-001"],
    price: 0,
    transactionFeePct: 1.2,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 356,
    popularityScore: 53,
  },
  {
    sku: "BIZ-FX-001",
    name: "International Payments & FX",
    navLabel: "International & FX",
    category: "Business",
    subcategory: "International",
    productType: "FX Service",
    url: "/products/business/international-payments-fx",
    accent: "#4F46E5",
    badge: "0.4% FX markup",
    segment: "business",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "Pay suppliers and receive payments in 30+ currencies at a 0.4% FX markup, with local account details in EUR, USD and GBP.",
    cardDescription:
      "Pay and get paid worldwide — 30+ currencies, local account details, and a 0.4% FX markup.",
    tagline: "Trade across borders without paying bank rates for the privilege.",
    longDescription:
      "International Payments & FX gives your business local account details in EUR, USD and GBP, so customers abroad pay you like a local, and lets you pay suppliers in 30+ currencies at the mid-market rate plus 0.4%. Hold balances in multiple currencies, set rate alerts, and lock a rate in advance with forward contracts for larger invoices.",
    displayPrice: "0.4% FX markup",
    access: "Same-day for major currencies",
    specs: [
      { label: "FX markup", value: "0.4% over mid-market" },
      { label: "Currencies", value: "30+ to pay, 3 to receive locally" },
      { label: "Speed", value: "Same day for EUR, USD, GBP" },
    ],
    perks: [
      "0.4% over the mid-market rate",
      "Local account details in EUR, USD and GBP",
      "Hold and pay in 30+ currencies",
      "Rate alerts and forward contracts",
      "No receiving fees",
    ],
    features: [
      "Multi-currency balances with local receiving details in EUR, USD and GBP",
      "Payments in 30+ currencies at mid-market plus 0.4%",
      "Forward contracts to lock a rate for up to 12 months",
      "Rate alerts and scheduled conversions",
      "Batch supplier payments from a single upload",
    ],
    eligibility: [
      "Active NexaBank Business Current Account",
      "Registered business in the EU",
      "Enhanced due diligence completed for forward contracts",
      "Authorised signatory verified",
    ],
    faq: [
      {
        q: "How does 0.4% compare?",
        a: "Traditional banks typically charge 2–3% on the exchange rate plus a transfer fee; we charge 0.4% and no transfer fee.",
      },
      {
        q: "Can I get paid in dollars without a US bank?",
        a: "Yes — your account comes with US local details so American customers pay you domestically.",
      },
      {
        q: "What is a forward contract?",
        a: "An agreement to exchange at today's rate on a future date, so a large invoice cannot be hit by a rate move.",
      },
    ],
    keywords: [
      "international payments",
      "business FX",
      "foreign exchange",
      "multi-currency account",
      "pay suppliers abroad",
      "USD account",
      "GBP account",
      "forward contract",
      "import export",
      "cross-border payments",
      "SWIFT",
    ],
    feeSummary: "0.4% FX markup · no transfer or receiving fees",
    regulatoryNote: "Forward contracts subject to eligibility and margin requirements.",
    personas: ["business"],
    goals: ["business_growth", "spend"],
    relatedSkus: ["BIZ-ACC-001", "BIZ-POS-001", "SVC-FX-001"],
    price: 0,
    fxFeePct: 0.4,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 221,
    popularityScore: 42,
  },
]);
