import { defineProducts } from "./types";

const REGULATORY = "Credit subject to status. Representative APR varies by card and credit profile.";

export const CARDS = defineProducts([
  {
    sku: "CARD-START-001",
    name: "NexaStart Card",
    shortName: "NexaStart",
    navLabel: "NexaStart",
    category: "Cards",
    subcategory: "Free",
    productType: "Credit Card",
    url: "/products/credit-cards/nexa-start",
    accent: "#16A34A",
    segment: "personal",
    tier: "free",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "Start your credit journey with no annual fee and 1% cashback on every purchase from day one.",
    cardDescription: "Start your credit journey with no annual fee and real cashback.",
    tagline: "Start your credit journey with no annual fee and real cashback from day one.",
    longDescription:
      "NexaStart is built for first-time card holders and anyone rebuilding their credit history. There's no annual fee, no minimum income requirement, and you earn 1% cashback on every purchase from the moment your card arrives. Spending insights in the app help you stay on top of your balance and build healthy habits.",
    displayPrice: "€0/year",
    perks: [
      "No annual fee, ever",
      "1% cashback on all purchases",
      "Build your credit history",
      "Spending insights in the app",
      "Apple Pay & Google Pay",
    ],
    features: [
      "No annual fee, ever",
      "1% cashback on all purchases, paid monthly",
      "Build or rebuild your credit score",
      "Real-time spending insights in the NexaBank app",
      "Apple Pay and Google Pay supported",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Valid government-issued ID",
      "Active NexaBank current account",
      "No active bankruptcy proceedings",
    ],
    faq: [
      {
        q: "Is there really no annual fee?",
        a: "None — NexaStart is free for as long as you hold it. You only pay interest if you carry a balance.",
      },
      {
        q: "Will this help my credit score?",
        a: "Yes. Paying on time each month is reported to credit bureaus and builds your history.",
      },
      {
        q: "What is the credit limit?",
        a: "Up to €3,000, reviewed after six months of on-time payments.",
      },
    ],
    keywords: [
      "free card",
      "no fee",
      "student card",
      "cashback",
      "build credit",
      "entry level",
      "first credit card",
      "no annual fee",
      "beginner",
      "credit score",
      "starter card",
    ],
    feeSummary: "€0 annual fee · 2.5% FX markup · 0% APR promotional rate",
    regulatoryNote: REGULATORY,
    cardGradient: "linear-gradient(135deg, #14532d 0%, #052e16 100%)",
    personas: ["student", "young_professional"],
    goals: ["build_credit", "spend"],
    relatedSkus: ["ACC-STU-001", "SAV-ROUND-001", "CASH-REW-001"],
    rateType: "variable",
    price: 0,
    interestRate: 0,
    fxFeePct: 2.5,
    cashbackPercent: 1,
    maxAmount: 3000,
    riskLevel: 1,
    minAge: 18,
    minIncome: 0,
    customerRating: 4.5,
    reviewCount: 5120,
    popularityScore: 84,
  },
  {
    sku: "CARD-ESS-001",
    name: "NexaEssential Card",
    shortName: "NexaEssential",
    navLabel: "NexaEssential",
    category: "Cards",
    subcategory: "Essential",
    productType: "Credit Card",
    url: "/products/credit-cards/nexa-essential",
    accent: "#2563FF",
    segment: "personal",
    tier: "essential",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "Everyday versatility with basic travel cover and purchase protection up to €1,000 per item.",
    cardDescription: "Everyday versatility with travel cover and purchase protection.",
    tagline: "Everyday versatility with travel cover and purchase protection built in.",
    longDescription:
      "NexaEssential is the everyday card for people who want a reliable mid-tier credit card with the extras that matter: basic travel insurance, purchase protection up to €1,000, and round-the-clock fraud monitoring. A modest annual fee gets you a higher credit limit and more comprehensive cover than NexaStart.",
    displayPrice: "€49/year",
    perks: [
      "0.5% cashback on all purchases",
      "Basic travel insurance included",
      "Purchase protection up to €1,000",
      "Contactless & virtual card",
      "Fraud monitoring 24/7",
    ],
    features: [
      "0.5% cashback on all purchases",
      "Basic travel insurance included for cardholder",
      "Purchase protection up to €1,000 per item",
      "Contactless and virtual card numbers for online use",
      "24/7 fraud monitoring with instant alerts",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €2,000",
      "Active NexaBank current account",
      "Good credit history (no recent defaults)",
    ],
    faq: [
      {
        q: "What does purchase protection cover?",
        a: "Theft or accidental damage of items bought with the card, up to €1,000 per item, for 90 days.",
      },
      {
        q: "Is the travel insurance enough for a holiday?",
        a: "It covers the cardholder for medical emergencies and cancellations on short trips. Frequent travellers should look at NexaNomad.",
      },
      {
        q: "Can I get a virtual card for online shopping?",
        a: "Yes — generate single-use virtual card numbers in the app.",
      },
    ],
    keywords: [
      "essential",
      "everyday",
      "basic travel",
      "purchase protection",
      "low fee",
      "mid-tier card",
      "everyday credit card",
      "fraud protection",
      "virtual card",
      "contactless",
    ],
    feeSummary: "€49 annual fee · 2% FX markup · 19.9% APR",
    regulatoryNote: REGULATORY,
    cardGradient: "linear-gradient(135deg, #1e3a8a 0%, #0B0D12 100%)",
    personas: ["all", "family"],
    goals: ["spend", "protect"],
    relatedSkus: ["ACC-EVERY-001", "CASH-REW-001", "INS-TRAV-001"],
    rateType: "variable",
    price: 49,
    interestRate: 19.9,
    fxFeePct: 2,
    cashbackPercent: 0.5,
    maxAmount: 10000,
    riskLevel: 1,
    minAge: 18,
    minIncome: 24000,
    customerRating: 4.4,
    reviewCount: 3870,
    popularityScore: 76,
  },
  {
    sku: "CARD-NOM-001",
    name: "NexaNomad Card",
    shortName: "NexaNomad",
    navLabel: "NexaNomad",
    category: "Cards",
    subcategory: "Travel",
    productType: "Credit Card",
    url: "/products/credit-cards/nexa-nomad",
    accent: "#0891B2",
    badge: "Most Popular",
    segment: "personal",
    tier: "travel",
    launchedAt: "2022-05-01T00:00:00",
    description:
      "Made for travellers — no FX fees worldwide and two complimentary airport lounge visits per year.",
    cardDescription: "No FX fees, lounge access, and full travel cover — made for travellers.",
    tagline: "No FX fees, lounge access, and full travel cover — made for travellers.",
    longDescription:
      "NexaNomad removes the friction from international spending. There are no foreign transaction fees, ever, and you earn 1.5% cashback on every purchase whether at home or abroad. Two complimentary lounge visits per year and comprehensive travel and medical insurance round out a card designed for people who live across borders.",
    displayPrice: "€99/year",
    perks: [
      "1.5% cashback on all purchases",
      "No foreign transaction fees",
      "2 free airport lounge visits/year",
      "Comprehensive travel & medical insurance",
      "Emergency card replacement worldwide",
    ],
    features: [
      "1.5% cashback on all purchases",
      "No foreign transaction fees worldwide",
      "2 free airport lounge visits per year",
      "Comprehensive travel and medical insurance",
      "Emergency card replacement anywhere in the world",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €3,500",
      "Active NexaBank current account",
      "Excellent credit history",
    ],
    faq: [
      {
        q: "Are there really no FX fees?",
        a: "None — we pass on the Mastercard exchange rate with 0% markup, in any currency, any day of the week.",
      },
      {
        q: "How does lounge access work?",
        a: "Two visits per year at 1,300+ lounges via the app's lounge pass. Extra visits are €30 each.",
      },
      {
        q: "Is travel insurance included for my family?",
        a: "The cardholder and travelling family members are covered when the trip is paid with the card.",
      },
    ],
    keywords: [
      "travel",
      "nomad",
      "no fx fees",
      "lounge access",
      "travel insurance",
      "global",
      "abroad",
      "holiday card",
      "foreign transaction",
      "digital nomad",
      "expat",
      "frequent flyer",
    ],
    feeSummary: "€99 annual fee · 0% FX markup · 17.9% APR",
    regulatoryNote: REGULATORY,
    cardGradient: "linear-gradient(135deg, #164e63 0%, #0B0D12 100%)",
    personas: ["young_professional", "family"],
    goals: ["travel", "spend"],
    relatedSkus: ["INS-TRAV-001", "SVC-FX-001", "ACC-EVERY-001"],
    rateType: "variable",
    price: 99,
    interestRate: 17.9,
    fxFeePct: 0,
    cashbackPercent: 1.5,
    maxAmount: 20000,
    riskLevel: 1,
    minAge: 18,
    minIncome: 42000,
    customerRating: 4.8,
    reviewCount: 6430,
    popularityScore: 96,
  },
  {
    sku: "CARD-PRES-001",
    name: "NexaPrestige Card",
    shortName: "NexaPrestige",
    navLabel: "NexaPrestige",
    category: "Cards",
    subcategory: "Premium",
    productType: "Credit Card",
    url: "/products/credit-cards/nexa-prestige",
    accent: "#B45309",
    segment: "personal",
    tier: "premium",
    launchedAt: "2022-05-01T00:00:00",
    description: "Our most exclusive card — 24/7 concierge service and our highest cashback rate at 2%.",
    cardDescription: "Our most exclusive card — concierge service, maximum cover, premium perks.",
    tagline: "Our most exclusive card — concierge service, maximum cover, premium perks.",
    longDescription:
      "NexaPrestige is reserved for our most discerning clients. A dedicated 24/7 personal concierge, unlimited airport lounge access, our highest cashback rate, and the lowest APR in the range. Maximum insurance coverage means you can travel and spend with absolute confidence, knowing every detail is taken care of.",
    displayPrice: "€299/year",
    perks: [
      "2% cashback on all purchases",
      "24/7 personal concierge service",
      "Unlimited airport lounge access",
      "Maximum insurance coverage",
      "Dedicated priority support line",
    ],
    features: [
      "2% cashback on all purchases — our highest rate",
      "24/7 personal concierge service for any request",
      "Unlimited airport lounge access worldwide",
      "Maximum insurance coverage on travel, purchases and rentals",
      "Dedicated priority customer support line",
    ],
    eligibility: [
      "Aged 25 or over and EU resident",
      "Minimum net monthly income of €8,000",
      "Active NexaBank current account",
      "Excellent credit history and clean financial record",
    ],
    faq: [
      {
        q: "What can the concierge do?",
        a: "Restaurant and travel bookings, event tickets, gifts, itinerary changes — anything legal, any hour, in 12 languages.",
      },
      {
        q: "Does the annual fee pay for itself?",
        a: "At €15,000 of annual spend the 2% cashback alone covers the fee, before lounge access and insurance.",
      },
      {
        q: "Is there a metal card?",
        a: "Yes — NexaPrestige is issued in brushed titanium with a numberless face.",
      },
    ],
    keywords: [
      "premium",
      "prestige",
      "concierge",
      "black card",
      "high net worth",
      "maximum insurance",
      "exclusive",
      "metal card",
      "luxury",
      "unlimited lounge",
      "lowest APR",
      "priority support",
    ],
    feeSummary: "€299 annual fee · 0% FX markup · 14.9% APR",
    regulatoryNote: REGULATORY,
    cardGradient: "linear-gradient(135deg, #451a03 0%, #0B0D12 100%)",
    personas: ["pre_retirement", "hnw"],
    goals: ["spend", "travel"],
    relatedSkus: ["PB-REL-001", "INV-FUND-001", "INS-TRAV-001"],
    rateType: "variable",
    price: 299,
    interestRate: 14.9,
    fxFeePct: 0,
    cashbackPercent: 2,
    maxAmount: 100000,
    riskLevel: 1,
    minAge: 25,
    minIncome: 96000,
    customerRating: 4.9,
    reviewCount: 1215,
    popularityScore: 61,
  },
]);
