import { defineProducts } from "./types";

export const CASHBACK = defineProducts([
  {
    sku: "CASH-CARD-001",
    name: "Cashback Credit Card",
    navLabel: "Cashback Card",
    category: "Cashback",
    subcategory: "Cashback Card",
    productType: "Cashback Card",
    url: "/products/cashback/cashback-card",
    accent: "#EC4899",
    badge: "Flagship",
    segment: "personal",
    tier: "essential",
    launchedAt: "2023-03-01T00:00:00",
    description:
      "Elevated cashback — 3% on groceries and fuel, 1.5% on subscriptions and 1% on everything else.",
    cardDescription:
      "A dedicated cashback credit card with elevated rewards on groceries, fuel and online subscriptions.",
    tagline: "Elevated cashback on groceries, fuel and online subscriptions.",
    longDescription:
      "The Cashback Credit Card is a dedicated rewards card focused on the categories where people spend most. Earn 3% back on groceries and fuel, 1.5% on online subscriptions, and 1% on everything else. Cashback is credited as a statement credit at the end of each billing cycle — no points, no portals, no fuss.",
    displayPrice: "up to 3% cashback",
    perks: [
      "3% cashback on groceries and fuel",
      "1.5% cashback on online subscriptions",
      "1% cashback on everything else",
      "Cashback credited as statement credit monthly",
      "Apple Pay and Google Pay supported",
    ],
    features: [
      "3% cashback on groceries and fuel",
      "1.5% cashback on online subscriptions (Netflix, Spotify, etc.)",
      "1% cashback on everything else",
      "Cashback credited as statement credit each month",
      "Apple Pay and Google Pay supported",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €2,500",
      "Active NexaBank current account",
      "Good credit history (no recent defaults)",
    ],
    faq: [
      {
        q: "Is there a cap on cashback?",
        a: "Yes — €150 per month across all categories, which corresponds to roughly €5,000 of monthly spend.",
      },
      {
        q: "How is cashback paid?",
        a: "As a credit on your statement at the end of each billing cycle — nothing to redeem.",
      },
      {
        q: "Does it pay for itself?",
        a: "At €400 a month on groceries and fuel the 3% rate alone earns €144 a year, more than twice the €59 fee.",
      },
    ],
    keywords: [
      "cashback",
      "rewards",
      "earn back",
      "everyday spending",
      "groceries",
      "fuel",
      "cashback credit card",
      "supermarket",
      "petrol",
      "subscriptions",
      "money back",
      "family spending",
    ],
    feeSummary: "€59 annual fee · 2% FX markup · 19.9% APR",
    regulatoryNote: "Credit subject to status. Cashback rates and partner offers may change.",
    cardGradient: "linear-gradient(135deg, #831843 0%, #0B0D12 100%)",
    personas: ["all", "family"],
    goals: ["spend", "save"],
    relatedSkus: ["CASH-REW-001", "ACC-JOINT-001", "CARD-ESS-001"],
    rateType: "variable",
    price: 59,
    interestRate: 19.9,
    fxFeePct: 2,
    cashbackPercent: 3,
    cashbackMonthlyCap: 150,
    maxAmount: 15000,
    riskLevel: 1,
    minAge: 18,
    minIncome: 30000,
    customerRating: 4.6,
    reviewCount: 2980,
    popularityScore: 79,
  },
  {
    sku: "CASH-REW-001",
    name: "Cashback Rewards Programme",
    navLabel: "Rewards Programme",
    category: "Cashback",
    subcategory: "Rewards",
    productType: "Rewards Programme",
    url: "/products/cashback/rewards-programme",
    accent: "#DB2777",
    badge: "Partner brands",
    segment: "personal",
    tier: "free",
    launchedAt: "2023-03-01T00:00:00",
    description:
      "Stackable cashback at 300+ partner brands — free for all NexaBank customers and credited within 48 hours.",
    cardDescription:
      "Earn cashback on top of your card cashback by shopping with NexaBank partner brands. Free to join.",
    tagline: "Stackable cashback at 300+ partner brands — free for all NexaBank customers.",
    longDescription:
      "The Cashback Rewards Programme is a free loyalty layer that runs on top of whatever NexaBank card you carry. Activate an offer in the app before you shop, and you'll earn an extra 2–10% cashback at over 300 partner brands across travel, retail, dining and lifestyle. Rewards stack on top of any cashback your card already earns.",
    displayPrice: "Free to join",
    perks: [
      "Earn 2–10% extra at 300+ partner brands",
      "Stacks on top of card cashback",
      "Activate offers in one tap in the app",
      "Rewards credited within 48 hours of purchase",
      "Free for all NexaBank customers",
    ],
    features: [
      "Earn 2–10% extra cashback at 300+ partner brands",
      "Stacks on top of your card cashback",
      "Activate offers in one tap in the NexaBank app",
      "Rewards credited within 48 hours of purchase",
      "Free for every NexaBank customer — no fee, no minimum",
    ],
    eligibility: [
      "Active NexaBank current account",
      "Aged 18 or over and EU resident",
      "Marketing communications opt-in for partner alerts",
      "Eligible NexaBank card used for the qualifying purchase",
    ],
    faq: [
      {
        q: "Which brands are partners?",
        a: "300+ across travel, fashion, dining, electronics and groceries — the full list is in the app and updates weekly.",
      },
      {
        q: "Do I need to do anything before shopping?",
        a: "Tap 'Activate' on the offer in the app, then pay with any NexaBank card.",
      },
      {
        q: "Is there really no fee?",
        a: "None. Partners fund the cashback; NexaBank customers join for free.",
      },
    ],
    keywords: [
      "rewards",
      "loyalty",
      "cashback programme",
      "points",
      "partner offers",
      "deals",
      "discounts",
      "shopping rewards",
      "free to join",
      "brand offers",
    ],
    feeSummary: "Free · no minimum spend",
    regulatoryNote: "Cashback rates and partner offers may change. Check the app for current rates before purchase.",
    personas: ["all"],
    goals: ["spend", "save"],
    relatedSkus: ["CASH-CARD-001", "CARD-START-001", "ACC-EVERY-001"],
    price: 0,
    cashbackPercent: 10,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 5540,
    popularityScore: 90,
  },
]);
