import { defineProducts } from "./types";

const REGULATORY = "Crypto assets are highly volatile and unregulated in some jurisdictions. You may lose all your capital.";

export const CRYPTO = defineProducts([
  {
    sku: "CRYPTO-BTC-001",
    name: "Bitcoin",
    navLabel: "Bitcoin",
    category: "Crypto",
    subcategory: "Bitcoin",
    productType: "Cryptocurrency",
    url: "/products/crypto/bitcoin",
    accent: "#F59E0B",
    badge: "Most traded",
    segment: "personal",
    launchedAt: "2023-05-01T00:00:00",
    description:
      "Buy, sell and hold BTC directly from your NexaBank account with insured cold-storage custody.",
    cardDescription:
      "Buy, sell and hold BTC directly from your NexaBank account. Custody is fully insured and segregated.",
    tagline: "Buy, sell and hold BTC directly from your NexaBank account.",
    longDescription:
      "Bitcoin (BTC) is the original digital asset and the largest by market capitalisation. NexaBank gives you regulated, insured access to BTC with no hidden custody fee — keep your coins in our cold-storage vault, set up an auto-buy schedule, or withdraw to an external wallet whenever you want.",
    displayPrice: "0.7% spread",
    perks: [
      "Buy from €10 in one tap",
      "Insured cold-storage custody",
      "Auto-buy schedules (daily/weekly/monthly)",
      "Real-time price alerts",
      "Withdraw to an external wallet anytime",
    ],
    features: [
      "Buy from €10 in one tap",
      "Insured cold-storage custody",
      "Auto-buy schedules (daily, weekly, monthly)",
      "Real-time price alerts and watchlist",
      "Withdraw to an external wallet anytime",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Crypto risk acknowledgement signed at onboarding",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "Do I own the actual bitcoin?",
        a: "Yes — coins are held in segregated cold storage in your name, and you can withdraw them to your own wallet.",
      },
      {
        q: "What does it cost?",
        a: "A 0.7% spread on each buy or sell. No custody fee, no monthly fee.",
      },
      {
        q: "Is it safe?",
        a: "Custody is insured and offline, but the price of bitcoin itself is highly volatile — only invest what you can afford to lose.",
      },
    ],
    keywords: [
      "bitcoin",
      "BTC",
      "cryptocurrency",
      "digital asset",
      "store of value",
      "buy bitcoin",
      "crypto",
      "blockchain",
      "digital gold",
      "auto-buy",
      "cold storage",
    ],
    feeSummary: "0.7% spread · no custody fee",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "crypto"],
    goals: ["invest"],
    relatedSkus: ["CRYPTO-ETH-001", "CRYPTO-PORT-001", "INV-ETF-001"],
    liquidity: "instant",
    price: 0,
    transactionFeePct: 0.7,
    minAmount: 10,
    maxAmount: 250000,
    riskLevel: 9,
    minAge: 18,
    customerRating: 4.5,
    reviewCount: 4010,
    popularityScore: 83,
  },
  {
    sku: "CRYPTO-ETH-001",
    name: "Ethereum",
    navLabel: "Ethereum",
    category: "Crypto",
    subcategory: "Ethereum",
    productType: "Cryptocurrency",
    url: "/products/crypto/ethereum",
    accent: "#D97706",
    badge: "Staking eligible",
    segment: "personal",
    launchedAt: "2023-05-01T00:00:00",
    description:
      "Trade ETH and earn staking rewards inside your NexaBank account with insured cold-storage custody.",
    cardDescription:
      "Trade ETH and access staking rewards. Custody and execution handled by our regulated partner exchange.",
    tagline: "Trade ETH and earn staking rewards inside your NexaBank account.",
    longDescription:
      "Ethereum (ETH) is the second-largest digital asset and powers a wide range of decentralised applications. NexaBank gives you the same regulated, insured access as Bitcoin, with the added option to opt your ETH balance into staking and earn rewards paid weekly in ETH.",
    displayPrice: "0.8% spread",
    perks: [
      "Buy from €10 in one tap",
      "Earn staking rewards on ETH balances",
      "Insured cold-storage custody",
      "Auto-buy schedules (daily/weekly/monthly)",
      "Withdraw to an external wallet anytime",
    ],
    features: [
      "Buy from €10 in one tap",
      "Earn staking rewards on ETH balances",
      "Insured cold-storage custody",
      "Auto-buy schedules (daily, weekly, monthly)",
      "Withdraw to an external wallet anytime",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Crypto risk acknowledgement signed at onboarding",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "How do I earn staking rewards?",
        a: "Opt your ETH balance into Crypto Staking in one tap; rewards are paid weekly in ETH.",
      },
      {
        q: "What does it cost?",
        a: "A 0.8% spread on each buy or sell. No custody fee.",
      },
      {
        q: "Can I send ETH to my own wallet?",
        a: "Yes — withdrawals to external wallets are supported after a 24-hour security hold on new addresses.",
      },
    ],
    keywords: [
      "ethereum",
      "ETH",
      "smart contracts",
      "DeFi",
      "altcoin",
      "buy ethereum",
      "crypto",
      "staking",
      "web3",
      "digital asset",
    ],
    feeSummary: "0.8% spread · no custody fee",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "crypto"],
    goals: ["invest"],
    relatedSkus: ["CRYPTO-STAK-001", "CRYPTO-BTC-001", "CRYPTO-PORT-001"],
    liquidity: "instant",
    price: 0,
    transactionFeePct: 0.8,
    minAmount: 10,
    maxAmount: 250000,
    riskLevel: 9,
    minAge: 18,
    customerRating: 4.4,
    reviewCount: 2640,
    popularityScore: 71,
  },
  {
    sku: "CRYPTO-PORT-001",
    name: "Crypto Portfolio",
    navLabel: "Portfolio",
    category: "Crypto",
    subcategory: "Portfolio",
    productType: "Crypto Portfolio",
    url: "/products/crypto/crypto-portfolio",
    accent: "#B45309",
    badge: "Diversified",
    segment: "personal",
    launchedAt: "2023-09-01T00:00:00",
    description:
      "A pre-built basket of the top 10 cryptocurrencies, rebalanced monthly with an all-in 1% annual fee.",
    cardDescription:
      "A pre-built basket of major cryptocurrencies, rebalanced monthly. Diversified exposure in one product.",
    tagline: "A pre-built basket of major cryptocurrencies, rebalanced monthly.",
    longDescription:
      "Crypto Portfolio gives you diversified exposure to the top 10 cryptocurrencies by market cap in a single product. Our partner rebalances the basket every month, so you don't need to manage individual coins. A 1% all-in annual fee covers custody, rebalancing and execution.",
    displayPrice: "1.0% spread",
    perks: [
      "Pre-built basket of 10 major cryptos",
      "Monthly rebalancing by our partner",
      "All-in 1% annual management fee",
      "Single line in your portfolio view",
      "No need to manage individual coins",
    ],
    features: [
      "Pre-built basket of 10 major cryptocurrencies",
      "Monthly rebalancing handled by our partner",
      "All-in 1% annual management fee",
      "Shows as a single line in your portfolio view",
      "No need to research or manage individual coins",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €50",
      "Crypto risk acknowledgement signed at onboarding",
    ],
    faq: [
      {
        q: "Which coins are in the basket?",
        a: "The ten largest by market capitalisation, weighted by size and capped at 30% per coin, reviewed monthly.",
      },
      {
        q: "What are the fees?",
        a: "A 1.0% spread when you buy or sell, plus a 1% all-in annual fee that covers custody and rebalancing.",
      },
      {
        q: "Is this less risky than a single coin?",
        a: "Diversification reduces single-coin risk, but the basket remains highly volatile — it is still a crypto investment.",
      },
    ],
    keywords: [
      "crypto basket",
      "diversified crypto",
      "altcoins",
      "portfolio",
      "managed crypto",
      "top 10 crypto",
      "crypto index",
      "easy crypto",
      "rebalanced",
      "beginner crypto",
    ],
    feeSummary: "1.0% spread · 1% annual fee",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "crypto"],
    goals: ["invest"],
    relatedSkus: ["CRYPTO-BTC-001", "INV-ROBO-001", "CRYPTO-STAK-001"],
    liquidity: "instant",
    price: 0,
    transactionFeePct: 1,
    annualFeePct: 1,
    minAmount: 50,
    maxAmount: 250000,
    riskLevel: 8,
    minAge: 18,
    customerRating: 4.3,
    reviewCount: 980,
    popularityScore: 52,
  },
  {
    sku: "CRYPTO-STAK-001",
    name: "Crypto Staking",
    navLabel: "Staking",
    category: "Crypto",
    subcategory: "Staking",
    productType: "Crypto Staking",
    url: "/products/crypto/crypto-staking",
    accent: "#92400E",
    badge: "Passive yield",
    segment: "personal",
    launchedAt: "2023-09-01T00:00:00",
    description:
      "Earn passive rewards by locking ETH, SOL, ADA and other eligible assets — paid weekly in the staked asset.",
    cardDescription:
      "Earn passive rewards by locking eligible crypto assets. Rewards paid in the same asset, weekly.",
    tagline: "Earn passive rewards by locking eligible crypto assets.",
    longDescription:
      "Crypto Staking lets you put eligible holdings to work. Lock ETH, SOL, ADA and a growing list of other assets to earn rewards paid weekly in the same asset. Unstake any time, subject to the cooldown period for that asset. Projected yields are shown in the app before you commit.",
    displayPrice: "Up to 8% APY",
    access: "Unstake any time (cooldown applies)",
    perks: [
      "Earn rewards on ETH, SOL, ADA and more",
      "Rewards paid weekly in the staked asset",
      "Unstake any time (cooldown periods apply)",
      "View projected yield in the app",
      "No third-party validators — handled by our partner",
    ],
    features: [
      "Earn rewards on ETH, SOL, ADA and more",
      "Rewards paid weekly in the staked asset",
      "Unstake any time (cooldown periods apply)",
      "Projected yield shown in the app before committing",
      "Validators handled by our regulated partner",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum stake of €100 per asset",
      "Crypto risk acknowledgement signed at onboarding",
    ],
    faq: [
      {
        q: "How much can I earn?",
        a: "Up to 8% APY depending on the asset and network conditions; the app shows the current rate before you stake.",
      },
      {
        q: "How long does unstaking take?",
        a: "Between 1 and 7 days depending on the network's cooldown period.",
      },
      {
        q: "Is staking taxed?",
        a: "Rewards are generally taxable as income when received; the app produces an annual statement for your return.",
      },
    ],
    keywords: [
      "staking",
      "yield",
      "passive income",
      "crypto rewards",
      "earn crypto",
      "ETH staking",
      "SOL",
      "ADA",
      "APY",
      "proof of stake",
    ],
    feeSummary: "10% of rewards · no lock-in fee",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "crypto"],
    goals: ["invest"],
    relatedSkus: ["CRYPTO-ETH-001", "CRYPTO-BTC-001", "CRYPTO-PORT-001"],
    liquidity: "notice",
    price: 0,
    aer: 8,
    minAmount: 100,
    maxAmount: 100000,
    noticeDays: 7,
    riskLevel: 9,
    minAge: 18,
    customerRating: 4.3,
    reviewCount: 730,
    popularityScore: 47,
  },
]);
