import { defineProducts } from "./types";

const REGULATORY = "Cover subject to policy terms, exclusions and underwriting. Premiums shown are indicative.";

export const INSURANCE = defineProducts([
  {
    sku: "INS-LIFE-001",
    name: "Life Insurance",
    navLabel: "Life",
    category: "Insurance",
    subcategory: "Life",
    productType: "Life Insurance",
    url: "/products/insurance/life-insurance",
    accent: "#EA580C",
    badge: "Family protection",
    segment: "personal",
    launchedAt: "2022-09-01T00:00:00",
    description:
      "A lump-sum payout to your beneficiaries from €50,000 to €1,000,000 of cover with premiums fixed for the term.",
    cardDescription:
      "A lump-sum payout to your beneficiaries if the worst happens. Cover from €50,000 to €1,000,000.",
    tagline: "A lump-sum payout to your beneficiaries if the worst happens.",
    longDescription:
      "Life Insurance from NexaBank is straightforward cover designed for people with families or dependents. Choose level cover (a fixed amount) or decreasing cover (designed to track a mortgage), with optional critical illness rider to pay out earlier on diagnosis of a major illness. Premiums are fixed for the full term.",
    displayPrice: "from €8/month",
    specs: [
      { label: "Cover", value: "€50,000 – €1,000,000", listingValue: "€50K – €1M" },
      { label: "Premium", value: "from €8 / month" },
      { label: "Term", value: "10–30 years" },
    ],
    perks: [
      "Choice of level or decreasing cover",
      "Optional critical illness rider",
      "No medical exam for cover up to €150,000",
      "Premiums fixed for the full term",
      "Cover for one or two lives",
    ],
    features: [
      "Choice of level or decreasing cover",
      "Optional critical illness rider",
      "No medical exam for cover up to €150,000",
      "Premiums fixed for the full term",
      "Cover for one or two lives on a single policy",
    ],
    eligibility: [
      "Aged 18 to 65 at policy start",
      "EU resident",
      "Health questionnaire completed at application",
      "Active NexaBank current account",
    ],
    faq: [
      {
        q: "How much cover do I need?",
        a: "A common rule is 10× your annual income plus outstanding debts. Decreasing cover is designed to match a repayment mortgage.",
      },
      {
        q: "Do I need a medical?",
        a: "Not for cover up to €150,000 — a health questionnaire is enough. Above that we may ask for a GP report.",
      },
      {
        q: "Who receives the payout?",
        a: "The beneficiaries you name in the policy; you can change them at any time in the app.",
      },
    ],
    keywords: [
      "life insurance",
      "protection",
      "beneficiary",
      "death benefit",
      "family protection",
      "mortgage protection",
      "critical illness",
      "life cover",
      "protect my family",
      "new baby",
      "dependents",
    ],
    feeSummary: "from €8/month · premiums fixed for the term",
    regulatoryNote: REGULATORY,
    personas: ["family"],
    goals: ["protect", "family"],
    relatedSkus: ["LOAN-REAL-001", "INS-INC-001", "ACC-JOINT-001"],
    price: 96,
    monthlyFee: 8,
    minAmount: 50000,
    maxAmount: 1000000,
    minTermMonths: 120,
    termMonths: 360,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 1090,
    popularityScore: 62,
  },
  {
    sku: "INS-HOME-001",
    name: "Home Insurance",
    navLabel: "Home",
    category: "Insurance",
    subcategory: "Home",
    productType: "Home Insurance",
    url: "/products/insurance/home-insurance",
    accent: "#C2410C",
    badge: "Owners & renters",
    segment: "personal",
    launchedAt: "2022-09-01T00:00:00",
    description:
      "Buildings cover up to €1M and contents up to €100,000 — for owners and renters, with 24/7 home assistance.",
    cardDescription:
      "Buildings and contents cover for owners and renters. Flexible add-ons for accidental damage and valuables.",
    tagline: "Buildings and contents cover for owners and renters, with flexible add-ons.",
    longDescription:
      "Home Insurance covers the structure of your home and everything inside it. Specify high-value items individually, add accidental damage cover for a few euros a month, and rely on 24/7 emergency assistance for plumbing, electrical or lock-out emergencies. Available to owners and renters.",
    displayPrice: "from €12/month",
    specs: [
      { label: "Cover", value: "Buildings up to €1M", listingValue: "up to €1M" },
      { label: "Premium", value: "from €12 / month" },
      { label: "Term", value: "12-month renewable" },
    ],
    perks: [
      "Buildings cover up to €1M",
      "Contents cover up to €100,000",
      "Optional accidental damage cover",
      "Specified valuables add-on",
      "24/7 emergency home assistance",
    ],
    features: [
      "Buildings cover up to €1M",
      "Contents cover up to €100,000",
      "Optional accidental damage cover",
      "Specified valuables add-on for high-value items",
      "24/7 emergency home assistance included",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Property located within the EU",
      "Active NexaBank current account",
      "Property not used commercially",
    ],
    faq: [
      {
        q: "Do renters need buildings cover?",
        a: "No — renters choose contents-only cover; the landlord insures the building.",
      },
      {
        q: "Are bicycles and laptops covered outside the home?",
        a: "Yes, with the personal possessions add-on, up to €3,000 per item.",
      },
      {
        q: "How fast are claims paid?",
        a: "Most contents claims are settled within five working days of receiving the documents.",
      },
    ],
    keywords: [
      "home insurance",
      "buildings",
      "contents",
      "property",
      "home cover",
      "renters insurance",
      "apartment insurance",
      "house insurance",
      "burglary",
      "water damage",
      "moving house",
    ],
    feeSummary: "from €12/month · 12-month renewable",
    regulatoryNote: REGULATORY,
    personas: ["family", "young_professional"],
    goals: ["protect", "home"],
    relatedSkus: ["LOAN-REAL-001", "LOAN-RENO-001", "INS-LIFE-001"],
    price: 144,
    monthlyFee: 12,
    maxAmount: 1000000,
    termMonths: 12,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.5,
    reviewCount: 1540,
    popularityScore: 67,
  },
  {
    sku: "INS-TRAV-001",
    name: "Travel Insurance",
    navLabel: "Travel",
    category: "Insurance",
    subcategory: "Travel",
    productType: "Travel Insurance",
    url: "/products/insurance/travel-insurance",
    accent: "#F97316",
    badge: "Worldwide",
    segment: "personal",
    launchedAt: "2022-09-01T00:00:00",
    description:
      "Single-trip or annual multi-trip cover with worldwide medical up to €10M and an optional winter sports add-on.",
    cardDescription:
      "Single-trip or annual multi-trip cover, including winter sports and high-value gear. Comes free with NexaNomad.",
    tagline: "Single-trip or annual multi-trip cover, including winter sports.",
    longDescription:
      "Travel Insurance covers medical emergencies abroad, cancellation, curtailment, lost or delayed baggage, and personal liability. Add winter sports cover for the season, or upgrade to an annual multi-trip policy if you travel more than twice a year. Already free with the NexaNomad credit card.",
    displayPrice: "from €4/trip",
    premiumUnit: "trip",
    specs: [
      { label: "Cover", value: "Medical up to €10M", listingValue: "up to €10M medical" },
      { label: "Premium", value: "from €4 / trip" },
      { label: "Term", value: "Single or annual" },
    ],
    perks: [
      "Worldwide medical cover up to €10M",
      "Cancellation and curtailment cover",
      "Lost or delayed baggage protection",
      "Optional winter sports cover",
      "Free with NexaNomad credit card",
    ],
    features: [
      "Worldwide medical cover up to €10M",
      "Cancellation and curtailment cover",
      "Lost or delayed baggage protection",
      "Optional winter sports add-on",
      "Free with the NexaNomad credit card",
    ],
    eligibility: [
      "Aged 18 to 75 at trip start",
      "EU resident",
      "Trip starts and ends in the country of residence",
      "Pre-existing medical conditions declared",
    ],
    faq: [
      {
        q: "Single trip or annual?",
        a: "Annual multi-trip cover from €48 a year pays for itself if you travel three or more times.",
      },
      {
        q: "Is it included with NexaNomad?",
        a: "Yes — NexaNomad cardholders get annual multi-trip cover at no cost when the trip is paid with the card.",
      },
      {
        q: "Does it cover cancelled flights?",
        a: "Cancellation and curtailment are covered for insured reasons such as illness, and delays over 12 hours.",
      },
    ],
    keywords: [
      "travel insurance",
      "holiday",
      "trip",
      "medical",
      "cancellation",
      "luggage",
      "abroad",
      "ski insurance",
      "winter sports",
      "annual multi-trip",
      "backpacking",
      "flight delay",
    ],
    feeSummary: "from €4/trip · annual multi-trip from €48/year",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "family"],
    goals: ["travel", "protect"],
    relatedSkus: ["CARD-NOM-001", "SVC-FX-001", "INS-CAR-001"],
    price: 48,
    maxAmount: 10000000,
    termMonths: 12,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.4,
    reviewCount: 2230,
    popularityScore: 74,
  },
  {
    sku: "INS-INC-001",
    name: "Income Protection",
    navLabel: "Income Protection",
    category: "Insurance",
    subcategory: "Income",
    productType: "Income Protection",
    url: "/products/insurance/income-protection",
    accent: "#9A3412",
    badge: "Self-employed friendly",
    segment: "personal",
    launchedAt: "2023-02-01T00:00:00",
    description:
      "Tax-free monthly payouts replacing up to 70% of your pre-tax income if illness or injury stops you working.",
    cardDescription:
      "Replaces a portion of your income if you cannot work due to illness or injury. Tax-free monthly payouts.",
    tagline: "Replaces a portion of your income if illness or injury prevents you from working.",
    longDescription:
      "Income Protection pays a tax-free monthly benefit if you cannot work due to illness or injury. Cover up to 70% of your pre-tax income, choose a deferred period from 4 to 52 weeks, and add inflation-linking so your benefit keeps pace with rising costs. Particularly valuable for the self-employed.",
    displayPrice: "from €15/month",
    specs: [
      { label: "Cover", value: "Up to 70% of income", listingValue: "up to 70% of income" },
      { label: "Premium", value: "from €15 / month" },
      { label: "Term", value: "To retirement age" },
    ],
    perks: [
      "Tax-free monthly payouts",
      "Cover up to 70% of pre-tax income",
      "Available to employed and self-employed",
      "Choice of deferred periods from 4 to 52 weeks",
      "Optional inflation-linking on benefit amount",
    ],
    features: [
      "Tax-free monthly payouts",
      "Cover up to 70% of pre-tax income",
      "Available to employed and self-employed",
      "Choice of deferred periods from 4 to 52 weeks",
      "Optional inflation-linking on benefit amount",
    ],
    eligibility: [
      "Aged 18 to 60 at policy start",
      "EU resident",
      "In active employment or self-employment",
      "Health questionnaire completed at application",
    ],
    faq: [
      {
        q: "What is the deferred period?",
        a: "The time between stopping work and the first payout — 4 to 52 weeks. A longer deferred period lowers the premium.",
      },
      {
        q: "Does it cover stress or mental health?",
        a: "Yes — any illness or injury that stops you working, confirmed by a doctor, including mental health conditions.",
      },
      {
        q: "How long are payouts made for?",
        a: "Until you return to work, reach the policy end age or the benefit term ends, whichever comes first.",
      },
    ],
    keywords: [
      "income protection",
      "disability",
      "sick pay",
      "salary protection",
      "long term",
      "self-employed",
      "freelancer",
      "can't work",
      "illness cover",
      "loss of income",
      "accident",
    ],
    feeSummary: "from €15/month · benefit tax-free",
    regulatoryNote: REGULATORY,
    personas: ["all", "business"],
    goals: ["protect"],
    relatedSkus: ["INS-LIFE-001", "BIZ-ACC-001", "SAV-INST-001"],
    price: 180,
    monthlyFee: 15,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.5,
    reviewCount: 620,
    popularityScore: 45,
  },
  {
    sku: "INS-CAR-001",
    name: "Car Insurance",
    navLabel: "Car",
    category: "Insurance",
    subcategory: "Car",
    productType: "Car Insurance",
    url: "/products/insurance/car-insurance",
    accent: "#EA580C",
    badge: "Instant quote",
    segment: "personal",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "Comprehensive car insurance from €18 a month with a 5-minute quote, EV battery cover and a courtesy car as standard.",
    cardDescription:
      "Comprehensive cover from €18 a month with a five-minute quote and a courtesy car as standard.",
    tagline: "Comprehensive cover, a five-minute quote, and a courtesy car when you need one.",
    longDescription:
      "Car Insurance from NexaBank is comprehensive by default: accidental damage, fire, theft, third-party liability and windscreen repair, with a courtesy car while yours is off the road. Electric vehicles get battery and charging-cable cover as standard. Get a quote in five minutes in the app, and if you financed the car with us, your policy renews alongside the loan.",
    displayPrice: "from €18/month",
    specs: [
      { label: "Cover", value: "Vehicles up to €100,000", listingValue: "up to €100K" },
      { label: "Premium", value: "from €18 / month" },
      { label: "Term", value: "12-month renewable" },
    ],
    perks: [
      "Comprehensive cover as standard",
      "Courtesy car while yours is repaired",
      "EV battery and charging-cable cover",
      "Windscreen repair with no excess",
      "Quote in five minutes in the app",
    ],
    features: [
      "Comprehensive cover: damage, fire, theft and third-party liability",
      "Courtesy car for the duration of repairs",
      "Electric-vehicle battery and charging-cable cover included",
      "Windscreen repair with no excess",
      "Optional protected no-claims bonus and legal cover",
    ],
    eligibility: [
      "Aged 21 or over and EU resident",
      "Full driving licence held for at least one year",
      "Vehicle registered in the EU",
      "Active NexaBank current account",
    ],
    faq: [
      {
        q: "Do you insure electric cars?",
        a: "Yes — battery, charging cable and home charger cover are included at no extra cost.",
      },
      {
        q: "Can I pay monthly?",
        a: "Yes, at no extra cost. Annual payment gets a 5% discount.",
      },
      {
        q: "What if I financed the car with NexaBank?",
        a: "Your policy is linked to the loan and can renew automatically until the finance ends.",
      },
    ],
    keywords: [
      "car insurance",
      "motor insurance",
      "auto insurance",
      "comprehensive",
      "electric car insurance",
      "courtesy car",
      "third party",
      "new driver",
      "vehicle cover",
      "windscreen",
    ],
    feeSummary: "from €18/month · 5% discount for annual payment",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "family"],
    goals: ["protect", "spend"],
    relatedSkus: ["LOAN-VEH-001", "INS-HOME-001", "ACC-EVERY-001"],
    price: 216,
    monthlyFee: 18,
    maxAmount: 100000,
    termMonths: 12,
    riskLevel: 1,
    minAge: 21,
    customerRating: 4.5,
    reviewCount: 173,
    popularityScore: 56,
  },
  {
    sku: "INS-PET-001",
    name: "Pet Insurance",
    navLabel: "Pet",
    category: "Insurance",
    subcategory: "Pet",
    productType: "Pet Insurance",
    url: "/products/insurance/pet-insurance",
    accent: "#F97316",
    badge: "Lifetime cover",
    segment: "personal",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "Lifetime pet insurance from €9 a month covering vet fees up to €8,000 a year for cats and dogs, with direct payment to the vet.",
    cardDescription:
      "Vet fees up to €8,000 a year for cats and dogs, paid directly to the vet — from €9 a month.",
    tagline: "Because they're family too — lifetime vet-fee cover from €9 a month.",
    longDescription:
      "Pet Insurance covers vet fees for illness and injury up to €8,000 a year, renewing for life so long-term conditions stay covered. We pay the vet directly at over 2,000 partner practices, include a 24/7 video-vet line, and cover dental illness, physiotherapy and third-party liability for dogs. Multi-pet households get 10% off each additional pet.",
    displayPrice: "from €9/month",
    specs: [
      { label: "Cover", value: "Vet fees up to €8,000 / year", listingValue: "up to €8K / year" },
      { label: "Premium", value: "from €9 / month" },
      { label: "Term", value: "Lifetime, 12-month renewable" },
    ],
    perks: [
      "Vet fees up to €8,000 a year",
      "Lifetime cover for ongoing conditions",
      "We pay partner vets directly",
      "24/7 video-vet line",
      "10% off each additional pet",
    ],
    features: [
      "Illness and injury vet fees up to €8,000 per year",
      "Lifetime cover — conditions stay covered at renewal",
      "Direct payment to 2,000+ partner practices",
      "Dental illness, physiotherapy and hydrotherapy included",
      "Third-party liability for dogs up to €1M",
    ],
    eligibility: [
      "Cat or dog aged 8 weeks to 8 years at policy start",
      "Pet microchipped and vaccinated",
      "Owner aged 18 or over and EU resident",
      "Active NexaBank current account",
    ],
    faq: [
      {
        q: "Are pre-existing conditions covered?",
        a: "No — conditions your pet showed signs of before the policy start are excluded, as with all pet insurance.",
      },
      {
        q: "Do I have to pay the vet first?",
        a: "Not at partner practices — we settle directly. Elsewhere, upload the invoice and we reimburse within five days.",
      },
      {
        q: "Does the premium rise as my pet ages?",
        a: "Premiums increase gradually with age; we show the projected premium for the next three years at purchase.",
      },
    ],
    keywords: [
      "pet insurance",
      "dog insurance",
      "cat insurance",
      "vet fees",
      "puppy",
      "kitten",
      "lifetime cover",
      "animal health",
      "vet bills",
      "new pet",
    ],
    feeSummary: "from €9/month · 10% multi-pet discount",
    regulatoryNote: REGULATORY,
    personas: ["family"],
    goals: ["protect", "family"],
    relatedSkus: ["INS-HOME-001", "ACC-JOINT-001", "CASH-CARD-001"],
    price: 108,
    monthlyFee: 9,
    maxAmount: 8000,
    termMonths: 12,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 129,
    popularityScore: 43,
  },
]);
