import { defineProducts } from "./types";

const CAPITAL_AT_RISK = "Capital at risk. The value of investments can go down as well as up and you may get back less than you invest.";

export const INVESTMENTS = defineProducts([
  {
    sku: "INV-FUND-001",
    name: "Managed Funds",
    navLabel: "Managed Funds",
    category: "Investments",
    subcategory: "Funds",
    productType: "Investment Fund",
    url: "/products/investments/managed-funds",
    accent: "#7C3AED",
    badge: "Actively managed",
    segment: "personal",
    launchedAt: "2022-04-01T00:00:00",
    description:
      "Actively managed portfolios across equities, bonds and alternatives — built and rebalanced by our team.",
    cardDescription:
      "Actively managed portfolios across equities, bonds and alternatives. Built and rebalanced by our investment team.",
    tagline: "Actively managed portfolios across equities, bonds and alternatives.",
    longDescription:
      "Our Managed Funds are built and continuously rebalanced by our in-house investment team. Choose a risk profile from cautious to growth, and we diversify across asset classes, regions and currencies on your behalf. Monthly performance reports give you full transparency on holdings and trades.",
    displayPrice: "5–8% p.a. target",
    access: "Min. 3 years",
    perks: [
      "Diversified across asset classes and regions",
      "Continuous rebalancing by our investment team",
      "Choice of risk profile from cautious to growth",
      "Detailed monthly performance reports",
      "No exit fees after the first year",
    ],
    features: [
      "Diversified across asset classes and regions",
      "Continuous rebalancing by our investment team",
      "Choice of risk profile from cautious to growth",
      "Detailed monthly performance reports",
      "No exit fees after the first year",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €1,000",
      "Suitability questionnaire completed at onboarding",
    ],
    faq: [
      {
        q: "What does the fund invest in?",
        a: "Global equities, government and corporate bonds, and a small allocation to alternatives such as property and infrastructure.",
      },
      {
        q: "What are the fees?",
        a: "An all-in 0.85% a year. Exiting in the first year costs 1%; after that there are no exit fees.",
      },
      {
        q: "Can I choose a cautious version?",
        a: "Yes — three profiles (cautious, balanced, growth) with different equity weightings.",
      },
    ],
    keywords: [
      "managed fund",
      "active management",
      "diversified",
      "portfolio",
      "professional",
      "mutual fund",
      "balanced fund",
      "growth fund",
      "invest for the long term",
      "wealth building",
      "fund manager",
    ],
    feeSummary: "0.85% annual fee · no exit fee after year one",
    regulatoryNote: CAPITAL_AT_RISK,
    personas: ["family", "pre_retirement"],
    goals: ["invest"],
    relatedSkus: ["INV-ROBO-001", "INV-BOND-001", "SVC-COACH-001"],
    liquidity: "instant",
    price: 0,
    annualFeePct: 0.85,
    expectedReturnMin: 5,
    expectedReturnMax: 8,
    minAmount: 1000,
    minTermMonths: 36,
    riskLevel: 5,
    minAge: 18,
    customerRating: 4.5,
    reviewCount: 1480,
    popularityScore: 73,
  },
  {
    sku: "INV-ETF-001",
    name: "ETFs",
    navLabel: "ETFs",
    category: "Investments",
    subcategory: "ETFs",
    productType: "ETF",
    url: "/products/investments/etfs",
    accent: "#5B21B6",
    badge: "Self-directed",
    segment: "personal",
    launchedAt: "2022-04-01T00:00:00",
    description: "Trade 500+ global ETFs at a flat €1 commission with fractional shares from €50.",
    cardDescription:
      "Trade hundreds of global ETFs at low cost. Build your own diversified portfolio with full control.",
    tagline: "Trade hundreds of global ETFs at low cost — build your own portfolio.",
    longDescription:
      "Take full control of your portfolio with access to over 500 ETFs across global markets. Flat €1 commission per trade, fractional shares from €50 and auto-invest schedules let you build a diversified portfolio at any budget. Real-time analytics inside the app show allocation, performance and dividends.",
    displayPrice: "Market-linked",
    access: "No minimum",
    perks: [
      "Access to 500+ global ETFs",
      "Flat €1 commission per trade",
      "Fractional shares from €50",
      "Auto-invest schedules in any ETF",
      "Real-time portfolio analytics in the app",
    ],
    features: [
      "Access to 500+ global ETFs",
      "Flat €1 commission per trade",
      "Fractional shares from €50",
      "Auto-invest schedules in any ETF",
      "Real-time portfolio analytics in the app",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €50",
      "Suitability questionnaire completed at onboarding",
    ],
    faq: [
      {
        q: "What is an ETF?",
        a: "An exchange-traded fund holds a basket of assets — for example the 500 largest US companies — and trades like a single share.",
      },
      {
        q: "How much does it cost?",
        a: "€1 per trade, and each ETF carries its own ongoing charge (typically 0.05–0.4%). NexaBank charges no custody fee.",
      },
      {
        q: "Can I invest a fixed amount every month?",
        a: "Yes — set an auto-invest schedule from €50 per month into any ETF.",
      },
    ],
    keywords: [
      "ETF",
      "index fund",
      "passive",
      "low cost",
      "market tracker",
      "diversified",
      "S&P 500",
      "world index",
      "stocks",
      "fractional shares",
      "self-directed investing",
      "DIY investing",
    ],
    feeSummary: "€1 per trade · no custody fee",
    regulatoryNote: CAPITAL_AT_RISK,
    personas: ["young_professional", "crypto"],
    goals: ["invest"],
    relatedSkus: ["INV-ROBO-001", "INV-ESG-001", "SAV-ROUND-001"],
    liquidity: "instant",
    price: 0,
    minAmount: 50,
    riskLevel: 6,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 2760,
    popularityScore: 81,
  },
  {
    sku: "INV-ROBO-001",
    name: "Robo-Advisory Portfolio",
    navLabel: "Robo-Advisory",
    category: "Investments",
    subcategory: "Robo",
    productType: "Robo-Advisory",
    url: "/products/investments/robo-advisory",
    accent: "#9333EA",
    badge: "Hands-off",
    segment: "personal",
    launchedAt: "2022-04-01T00:00:00",
    description:
      "Tell us your goal — we build a diversified portfolio and rebalance it for you at 0.45% a year.",
    cardDescription:
      "Tell us your goal and risk appetite — we build a low-cost, diversified portfolio and rebalance it for you.",
    tagline: "Tell us your goal — we build the portfolio and rebalance it for you.",
    longDescription:
      "The Robo-Advisory Portfolio is the easiest way to start investing. A 5-minute questionnaire matches you to a risk profile, and we invest your money in a globally diversified portfolio of low-cost funds. We rebalance every quarter and harvest tax losses where local rules allow, all for a single 0.45% annual fee.",
    displayPrice: "4–7% p.a. target",
    access: "Min. 5 years",
    perks: [
      "5-minute setup questionnaire",
      "Low all-in fee of 0.45% per year",
      "Automatic rebalancing every quarter",
      "Tax-loss harvesting where available",
      "Top up or withdraw at any time, no penalty",
    ],
    features: [
      "5-minute setup questionnaire",
      "Low all-in fee of 0.45% per year",
      "Automatic rebalancing every quarter",
      "Tax-loss harvesting where available",
      "Top up or withdraw at any time, no penalty",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €500",
      "Suitability questionnaire completed at onboarding",
    ],
    faq: [
      {
        q: "How do you pick my portfolio?",
        a: "Your answers on goals, horizon and risk tolerance map to one of ten model portfolios, from 20% to 100% equities.",
      },
      {
        q: "Can I change my risk level later?",
        a: "Yes, at any time in the app. We rebalance you into the new model at the next trading window.",
      },
      {
        q: "Is 0.45% really all I pay?",
        a: "That is NexaBank's fee. The underlying funds average a further 0.15% ongoing charge.",
      },
    ],
    keywords: [
      "robo advisor",
      "automated",
      "algorithm",
      "smart investing",
      "digital",
      "beginner investing",
      "start investing",
      "hands-off",
      "risk profile",
      "goal based investing",
      "first investment",
    ],
    feeSummary: "0.45% annual fee · no entry or exit fees",
    regulatoryNote: CAPITAL_AT_RISK,
    personas: ["young_professional", "family"],
    goals: ["invest", "save"],
    relatedSkus: ["INV-ETF-001", "INV-FUND-001", "SVC-COACH-001"],
    liquidity: "instant",
    price: 0,
    annualFeePct: 0.45,
    expectedReturnMin: 4,
    expectedReturnMax: 7,
    minAmount: 500,
    minTermMonths: 60,
    riskLevel: 4,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 3340,
    popularityScore: 86,
  },
  {
    sku: "INV-PEN-001",
    name: "Investment Pension Plan",
    navLabel: "Investment Pension",
    category: "Investments",
    subcategory: "Pension",
    productType: "Investment Pension",
    url: "/products/investments/investment-pension",
    accent: "#6D28D9",
    badge: "Tax relief",
    segment: "personal",
    launchedAt: "2022-06-01T00:00:00",
    description:
      "A pension wrapper invested in our managed funds with tax relief on contributions up to the annual limit.",
    cardDescription:
      "A pension wrapper invested in our managed funds. Tax relief on contributions, projected income at retirement.",
    tagline: "A pension wrapper invested in our managed funds with tax relief on contributions.",
    longDescription:
      "The Investment Pension Plan combines the long-term growth of our Managed Funds with the tax efficiency of a pension wrapper. Contributions qualify for tax relief up to the annual limit, employer matching is supported, and a retirement income projection updates daily as markets move and you contribute.",
    displayPrice: "5–7% p.a. target",
    access: "Retirement age",
    contributionPeriod: "month",
    perks: [
      "Tax relief on contributions up to annual limit",
      "Choice of growth, balanced or income fund",
      "Employer matching supported",
      "Retirement income projection updated daily",
      "Consolidate pension pots from previous providers",
    ],
    features: [
      "Tax relief on contributions up to annual limit",
      "Choice of growth, balanced or income fund",
      "Employer contribution matching supported",
      "Retirement income projection updated daily",
      "Consolidate pension pots from previous providers",
    ],
    eligibility: [
      "Aged 18 or over and resident in the eligible jurisdiction",
      "Active NexaBank current account",
      "Minimum monthly contribution of €100",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "How is this different from the Pension Savings Plan?",
        a: "This plan is invested in funds for higher long-term growth potential; the Pension Savings Plan earns a fixed rate with no market risk.",
      },
      {
        q: "Does the risk reduce as I approach retirement?",
        a: "Yes — a lifestyle glide path moves you from growth to income funds over the last ten years, unless you switch it off.",
      },
      {
        q: "What does it cost?",
        a: "0.75% a year including fund charges. No entry or transfer-in fees.",
      },
    ],
    keywords: [
      "investment pension",
      "SIPP",
      "retirement",
      "long term growth",
      "tax relief",
      "pension fund",
      "retire early",
      "retirement income",
      "glide path",
      "PER",
      "pension investing",
    ],
    feeSummary: "0.75% annual fee · no entry fee",
    regulatoryNote: "Funds are locked until retirement age except in cases permitted by law. " + CAPITAL_AT_RISK,
    personas: ["pre_retirement", "young_professional"],
    goals: ["retire", "invest"],
    relatedSkus: ["SAV-PEN-001", "SVC-RETIRE-001", "INV-FUND-001"],
    liquidity: "retirement",
    price: 0,
    annualFeePct: 0.75,
    expectedReturnMin: 5,
    expectedReturnMax: 7,
    minAmount: 100,
    riskLevel: 4,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 890,
    popularityScore: 60,
  },
  {
    sku: "INV-BOND-001",
    name: "Bond Fund",
    navLabel: "Bond Fund",
    category: "Investments",
    subcategory: "Bonds",
    productType: "Investment Fund",
    url: "/products/investments/bond-fund",
    accent: "#4C1D95",
    badge: "Lower volatility",
    segment: "personal",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "A diversified fund of investment-grade government and corporate bonds targeting 3–5% a year with lower volatility than equities.",
    cardDescription:
      "Steady income from investment-grade government and corporate bonds — a calmer step up from savings.",
    tagline: "Income and stability — the calmer way to invest beyond savings.",
    longDescription:
      "The Bond Fund holds a diversified portfolio of investment-grade government and corporate bonds across the eurozone and developed markets. It targets 3–5% a year with far less volatility than equity funds, making it a natural next step for savers who want more than a deposit rate without taking equity risk. Income is distributed quarterly or reinvested automatically.",
    displayPrice: "3–5% p.a. target",
    access: "Min. 2 years",
    perks: [
      "Investment-grade government and corporate bonds",
      "Quarterly income or automatic reinvestment",
      "Low 0.35% annual fee",
      "Lower volatility than equity funds",
      "Sell any time, no exit fee",
    ],
    features: [
      "Diversified across 300+ eurozone and developed-market bonds",
      "Investment-grade only — no high-yield or emerging-market debt",
      "Choose quarterly income payments or accumulation",
      "0.35% annual fee, no entry or exit fees",
      "Daily pricing and same-day sell orders",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €500",
      "Suitability questionnaire completed at onboarding",
    ],
    faq: [
      {
        q: "Is a bond fund safe?",
        a: "Safer than equities but not guaranteed — bond prices fall when interest rates rise. It sits between a deposit and an equity fund on the risk scale.",
      },
      {
        q: "How is the income paid?",
        a: "Quarterly to your current account, or reinvested into the fund if you choose accumulation.",
      },
      {
        q: "Who is it for?",
        a: "Cautious investors, people nearing retirement, or anyone parking money for two to five years.",
      },
    ],
    keywords: [
      "bond fund",
      "bonds",
      "fixed income",
      "low risk investment",
      "cautious investor",
      "steady income",
      "government bonds",
      "corporate bonds",
      "capital preservation",
      "risk averse",
      "conservative",
    ],
    feeSummary: "0.35% annual fee · no entry or exit fees",
    regulatoryNote: CAPITAL_AT_RISK,
    personas: ["pre_retirement", "family"],
    goals: ["invest", "retire", "save"],
    relatedSkus: ["SAV-TERM-001", "INV-ROBO-001", "INV-FUND-001"],
    liquidity: "instant",
    price: 0,
    annualFeePct: 0.35,
    expectedReturnMin: 3,
    expectedReturnMax: 5,
    minAmount: 500,
    minTermMonths: 24,
    riskLevel: 3,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 142,
    popularityScore: 49,
  },
  {
    sku: "INV-ESG-001",
    name: "Sustainable Portfolio",
    navLabel: "Sustainable",
    category: "Investments",
    subcategory: "Sustainable",
    productType: "Robo-Advisory",
    url: "/products/investments/sustainable-portfolio",
    accent: "#059669",
    badge: "ESG screened",
    segment: "personal",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "A globally diversified, ESG-screened portfolio that excludes fossil fuels, tobacco and weapons — targeting 5–8% a year from €250.",
    cardDescription:
      "Invest in line with your values — a diversified portfolio that excludes fossil fuels, tobacco and weapons.",
    tagline: "Grow your money without compromising your values.",
    longDescription:
      "The Sustainable Portfolio invests in companies with strong environmental, social and governance scores and excludes fossil-fuel producers, tobacco, weapons and gambling. It is built from low-cost ESG index funds, diversified across regions and sectors, and rebalanced quarterly like our Robo-Advisory Portfolio. An impact report in the app shows the carbon intensity of your holdings versus the market.",
    displayPrice: "5–8% p.a. target",
    access: "Min. 5 years",
    perks: [
      "Excludes fossil fuels, tobacco, weapons and gambling",
      "Globally diversified ESG index funds",
      "Quarterly rebalancing",
      "Impact report in the app",
      "Start from €250",
    ],
    features: [
      "Strict exclusion screens plus best-in-class ESG selection",
      "Built from low-cost ESG index funds across all regions",
      "Automatic quarterly rebalancing",
      "Personal impact report with carbon intensity vs. the market",
      "0.6% all-in annual fee, no entry or exit fees",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum investment of €250",
      "Suitability questionnaire completed at onboarding",
    ],
    faq: [
      {
        q: "Does sustainable mean lower returns?",
        a: "Not necessarily — the portfolio targets the same 5–8% range as our growth strategies; sector weights simply differ.",
      },
      {
        q: "How do you decide what to exclude?",
        a: "Fixed exclusions (fossil fuels, tobacco, weapons, gambling) plus a minimum ESG rating from an independent provider.",
      },
      {
        q: "Can I see the actual holdings?",
        a: "Yes — every fund and its top holdings are listed in the app, updated monthly.",
      },
    ],
    keywords: [
      "sustainable investing",
      "ESG",
      "ethical investing",
      "green investing",
      "impact",
      "climate",
      "socially responsible",
      "no fossil fuels",
      "responsible portfolio",
      "values",
    ],
    feeSummary: "0.6% annual fee · no entry or exit fees",
    regulatoryNote: CAPITAL_AT_RISK,
    personas: ["young_professional", "family"],
    goals: ["invest"],
    relatedSkus: ["INV-ROBO-001", "LOAN-GREEN-001", "INV-ETF-001"],
    liquidity: "instant",
    price: 0,
    annualFeePct: 0.6,
    expectedReturnMin: 5,
    expectedReturnMax: 8,
    minAmount: 250,
    minTermMonths: 60,
    riskLevel: 5,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 268,
    popularityScore: 63,
  },
  {
    sku: "INV-JUN-001",
    name: "Junior Investment Plan",
    navLabel: "Junior Investment",
    category: "Investments",
    subcategory: "Junior",
    productType: "Robo-Advisory",
    url: "/products/investments/junior-investment-plan",
    accent: "#0D9488",
    badge: "For under-18s",
    segment: "kids",
    launchedAt: "2026-08-01T00:00:00",
    description:
      "A long-term investment plan in a child's name from €25 a month — a diversified portfolio that becomes theirs at 18.",
    cardDescription:
      "Invest for your child's future from €25 a month. Diversified, low-cost, and theirs at 18.",
    tagline: "Eighteen years is a long time to grow — start their future today.",
    longDescription:
      "The Junior Investment Plan lets parents and grandparents invest for a child over the long horizon that makes markets work best. Contributions from €25 a month go into a globally diversified portfolio that de-risks automatically as the child approaches 18, when the plan transfers to them. Family and friends can gift into it, and the child follows the goal in NexaKids.",
    displayPrice: "4–7% p.a. target",
    access: "Until age 18",
    contributionPeriod: "month",
    perks: [
      "From €25 a month",
      "Diversified global portfolio",
      "De-risks automatically before 18",
      "Gift link for family and friends",
      "Transfers to the child at 18",
    ],
    features: [
      "Globally diversified portfolio of low-cost index funds",
      "Automatic glide path from growth to cautious over the final five years",
      "Contributions from parents, grandparents and friends via gift link",
      "Goal tracking the child can follow in NexaKids",
      "0.5% all-in annual fee, no entry fee",
    ],
    eligibility: [
      "Child aged 0 to 17",
      "Parent or legal guardian holds an active NexaBank current account",
      "Minimum contribution of €25 per month",
      "One Junior Investment Plan per child",
    ],
    faq: [
      {
        q: "Can the money be taken out before 18?",
        a: "No — the plan is locked until the child turns 18, which is what allows the long-term growth.",
      },
      {
        q: "What happens at 18?",
        a: "The plan becomes the child's own investment account; they can keep investing, withdraw, or move to another product.",
      },
      {
        q: "Is it risky?",
        a: "It holds equities, so values move. Over an 18-year horizon that volatility has historically been rewarded, and the glide path reduces risk near the end.",
      },
    ],
    keywords: [
      "junior investment",
      "invest for my child",
      "kids investment plan",
      "children's future",
      "grandchild",
      "university fund",
      "long term investing",
      "gift for a child",
      "under 18",
      "start early",
    ],
    feeSummary: "0.5% annual fee · no entry fee",
    regulatoryNote: "Locked until the child turns 18. " + CAPITAL_AT_RISK,
    personas: ["family", "kids_teens"],
    goals: ["kids", "invest", "education"],
    relatedSkus: ["SAV-JUN-001", "ACC-KIDS-001", "INV-ROBO-001"],
    liquidity: "term",
    price: 0,
    annualFeePct: 0.5,
    expectedReturnMin: 4,
    expectedReturnMax: 7,
    minAmount: 25,
    riskLevel: 4,
    minAge: 0,
    customerRating: 4.8,
    reviewCount: 97,
    popularityScore: 41,
  },
]);
