import { defineProducts } from "./types";

const REGULATORY = "Credit subject to status and affordability checks. Representative APR shown; your rate may vary.";

export const LOANS = defineProducts([
  {
    sku: "LOAN-REAL-001",
    name: "Real Estate Loan",
    navLabel: "Real Estate",
    category: "Loans",
    subcategory: "Real Estate",
    productType: "Real Estate Loan",
    url: "/products/loans/real-estate-loan",
    imageUrl: "/loans/real-estate-loan.jpg",
    accent: "#2563FF",
    badge: "Up to 90% LTV",
    segment: "personal",
    launchedAt: "2022-03-01T00:00:00",
    description:
      "Your home journey starts here — competitive rates and long-term flexibility with terms up to 30 years.",
    cardDescription:
      "Finance your property purchase with competitive fixed and variable rates and terms up to 30 years.",
    tagline: "Your home journey starts here — competitive rates, long-term flexibility.",
    longDescription:
      "From first-time buyers to seasoned investors, our Real Estate Loan offers competitive rates and the flexibility to match your project. Choose between fixed and variable rates, borrow up to 90% of the property value, and benefit from a free valuation included with every application.",
    displayPrice: "from 3.9% APR",
    perks: [],
    features: [
      "Fixed and variable rate options",
      "Up to 90% loan-to-value",
      "Free property valuation included",
      "Dedicated mortgage advisor throughout the process",
      "No early repayment fee on variable rate",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €2,500",
      "Property located within the EU",
      "Proof of deposit (minimum 10%)",
    ],
    faq: [
      {
        q: "How much deposit do I need?",
        a: "At least 10% of the property value. With a 10% deposit we lend up to 90% loan-to-value.",
      },
      {
        q: "Fixed or variable — which should I choose?",
        a: "Fixed gives you a known repayment for the fixed period; variable tracks the market and has no early repayment fee. A mortgage advisor walks you through both.",
      },
      {
        q: "How long does approval take?",
        a: "Most applications receive an agreement in principle within 48 hours once documents are uploaded in the app.",
      },
    ],
    keywords: [
      "mortgage",
      "real estate",
      "property",
      "home purchase",
      "home loan",
      "first buyer",
      "first home",
      "buy a house",
      "buy an apartment",
      "buy-to-let",
      "fixed rate mortgage",
      "loan to value",
    ],
    feeSummary: "No arrangement fee · free valuation · no early repayment fee on variable rate",
    regulatoryNote: REGULATORY,
    tools: ["loan-calculator"],
    personas: ["family", "young_professional"],
    goals: ["home", "borrow", "family"],
    relatedSkus: ["INS-HOME-001", "INS-LIFE-001", "SVC-MORT-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 3.9,
    minAmount: 50000,
    maxAmount: 3000000,
    minTermMonths: 60,
    termMonths: 360,
    riskLevel: 1,
    minAge: 18,
    minIncome: 30000,
    customerRating: 4.7,
    reviewCount: 2140,
    popularityScore: 92,
  },
  {
    sku: "LOAN-VEH-001",
    name: "Vehicle Financing",
    navLabel: "Vehicle",
    category: "Loans",
    subcategory: "Vehicle",
    productType: "Vehicle Financing",
    url: "/products/loans/car-loan",
    imageUrl: "/loans/car-loan.jpg",
    accent: "#0891B2",
    badge: "Same-day approval",
    segment: "personal",
    launchedAt: "2022-03-01T00:00:00",
    description: "Drive away sooner with flexible financing for new and used cars up to €75,000.",
    cardDescription:
      "Drive away sooner with flexible financing for new and used cars, with same-day approval decisions.",
    tagline: "Drive away sooner with flexible financing for new and used cars.",
    longDescription:
      "Whether you're buying new or used, our Vehicle Financing gives you the freedom to choose the car you want at a rate that works for you. Get a same-day approval decision, with no hidden fees and fixed monthly repayments across terms of up to 72 months.",
    displayPrice: "from 5.5% APR",
    specs: [{ label: "Term", value: "12 – 72 months" }],
    perks: [],
    features: [
      "Same-day approval decision",
      "Finance new and used vehicles up to €75,000",
      "No early repayment penalty",
      "Fixed monthly payments for the full term",
      "Dedicated loan advisor on request",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €1,500",
      "Valid driving licence",
      "No recent adverse credit history",
    ],
    faq: [
      {
        q: "Can I finance a used car?",
        a: "Yes — new and used vehicles up to €75,000, including private sales with a valid purchase agreement.",
      },
      {
        q: "Can I repay early?",
        a: "Yes, at any time and without penalty. Interest stops the day you settle.",
      },
      {
        q: "Do you need a deposit?",
        a: "No deposit is required; many customers put one down to lower their monthly repayment.",
      },
    ],
    keywords: [
      "car loan",
      "vehicle",
      "auto",
      "financing",
      "new car",
      "used car",
      "car finance",
      "electric car",
      "motorbike",
      "buy a car",
      "same day approval",
    ],
    feeSummary: "No arrangement fee · no early repayment penalty",
    regulatoryNote: REGULATORY,
    personas: ["young_professional", "family"],
    goals: ["borrow", "spend"],
    relatedSkus: ["INS-CAR-001", "ACC-EVERY-001", "CARD-ESS-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 5.5,
    minAmount: 3000,
    maxAmount: 75000,
    minTermMonths: 12,
    termMonths: 72,
    riskLevel: 1,
    minAge: 18,
    minIncome: 18000,
    customerRating: 4.6,
    reviewCount: 1385,
    popularityScore: 78,
  },
  {
    sku: "LOAN-SHORT-001",
    name: "Short Term Loan",
    navLabel: "Short Term",
    category: "Loans",
    subcategory: "Short Term",
    productType: "Short Term Loan",
    url: "/products/loans/short-term-loan",
    imageUrl: "/loans/short-term-loan.jpg",
    accent: "#EA580C",
    badge: "Funds in 24h",
    segment: "personal",
    launchedAt: "2022-03-01T00:00:00",
    description: "Fast funds when you need them — in your account within 24 hours of approval.",
    cardDescription:
      "Fast funds in 24 hours for unexpected expenses. No collateral required, minimal paperwork.",
    tagline: "Fast funds when you need them — in your account within 24 hours.",
    longDescription:
      "Life doesn't always wait. Our Short Term Loan puts money in your account within 24 hours of approval, with minimal paperwork and no collateral required. A straightforward repayment schedule means no surprises — just the funds you need, when you need them.",
    displayPrice: "from 8.9% APR",
    perks: [],
    features: [
      "Funds credited within 24 hours of approval",
      "No collateral or guarantor required",
      "Minimal documentation — apply entirely online",
      "Flexible repayment schedule from 1 to 24 months",
      "Early repayment at no additional cost",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Minimum net monthly income of €1,000",
      "No active loan defaults",
    ],
    faq: [
      {
        q: "How fast will I get the money?",
        a: "Within 24 hours of approval, paid straight into your NexaBank current account.",
      },
      {
        q: "Is there a fee for paying it off early?",
        a: "No. You can repay in full at any point at no additional cost.",
      },
      {
        q: "What can I use it for?",
        a: "Anything unexpected — a repair, a deposit, a bill — as long as it is not for business purposes.",
      },
    ],
    keywords: [
      "short term",
      "quick loan",
      "emergency",
      "fast cash",
      "instant",
      "unexpected expense",
      "small loan",
      "bridge",
      "urgent money",
      "no collateral",
    ],
    feeSummary: "No arrangement fee · no early repayment cost",
    regulatoryNote: REGULATORY,
    personas: ["all", "young_professional"],
    goals: ["borrow"],
    relatedSkus: ["ACC-EVERY-001", "SAV-INST-001", "CARD-START-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 8.9,
    minAmount: 500,
    maxAmount: 10000,
    minTermMonths: 1,
    termMonths: 24,
    riskLevel: 1,
    minAge: 18,
    minIncome: 12000,
    customerRating: 4.4,
    reviewCount: 3210,
    popularityScore: 70,
  },
  {
    sku: "LOAN-STU-001",
    name: "Student Loan",
    navLabel: "Student",
    category: "Loans",
    subcategory: "Education",
    productType: "Student Loan",
    url: "/products/loans/student-loan",
    imageUrl: "/loans/student-loan.jpg",
    accent: "#16A34A",
    badge: "Deferred repayment",
    segment: "personal",
    launchedAt: "2022-09-01T00:00:00",
    description:
      "Invest in your education — our lowest rate at 2.9% APR with deferred repayment until after graduation.",
    cardDescription:
      "Invest in your future with low-rate education financing and flexible deferred repayment options.",
    tagline: "Invest in your education — our lowest rates, built for students.",
    longDescription:
      "Our Student Loan is designed to remove financial barriers to education. With our lowest available rate and the option to defer repayments until after you graduate, you can focus on your studies without the pressure of immediate repayments. Covers tuition fees, accommodation, and living expenses.",
    displayPrice: "from 2.9% APR",
    perks: [],
    features: [
      "Defer repayments until 6 months after graduation",
      "Our lowest rate — from 2.9% APR",
      "Covers tuition, accommodation and living costs",
      "No early repayment penalty",
      "Flexible repayment terms up to 10 years",
    ],
    eligibility: [
      "Aged 17 or over and EU resident",
      "Enrolled in an accredited university or institution",
      "Co-signatory required for applicants under 18",
      "Annual enrolment confirmation required",
    ],
    faq: [
      {
        q: "When do repayments start?",
        a: "Six months after you graduate or leave your course. Interest accrues during your studies but nothing is due.",
      },
      {
        q: "Can I use it for living costs?",
        a: "Yes — tuition, accommodation and everyday living expenses are all covered.",
      },
      {
        q: "Do I need a guarantor?",
        a: "Only if you are under 18, in which case a co-signatory is required.",
      },
    ],
    keywords: [
      "student loan",
      "education",
      "university",
      "tuition",
      "study",
      "college",
      "masters",
      "erasmus",
      "student finance",
      "deferred repayment",
      "graduate",
    ],
    feeSummary: "No arrangement fee · no early repayment penalty",
    regulatoryNote: REGULATORY,
    personas: ["student"],
    goals: ["education", "borrow"],
    relatedSkus: ["ACC-STU-001", "CARD-START-001", "SAV-ROUND-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 2.9,
    minAmount: 1000,
    maxAmount: 25000,
    minTermMonths: 12,
    termMonths: 120,
    riskLevel: 1,
    minAge: 17,
    minIncome: 0,
    customerRating: 4.8,
    reviewCount: 960,
    popularityScore: 64,
  },
  {
    sku: "LOAN-RENO-001",
    name: "House Renovation Loan",
    navLabel: "Renovation",
    category: "Loans",
    subcategory: "Home Improvement",
    productType: "House Renovation Loan",
    url: "/products/loans/renovation-loan",
    imageUrl: "/loans/renovation-loan.jpg",
    accent: "#7C3AED",
    badge: "Decision in 48h",
    segment: "personal",
    launchedAt: "2023-01-15T00:00:00",
    description:
      "Transform your home — from a kitchen remodel to a full refurbishment with stage-release funding.",
    cardDescription:
      "Transform your home with dedicated renovation financing at competitive rates and flexible terms.",
    tagline: "Transform your home — from kitchen to full refurbishment.",
    longDescription:
      "Whether you're planning a kitchen remodel, a new bathroom, or a full home refurbishment, our House Renovation Loan gives you the funds to bring your project to life. Choose your own contractor, receive a decision within 48 hours, and benefit from stage-release funding on larger projects.",
    displayPrice: "from 4.5% APR",
    perks: [],
    features: [
      "No restriction on contractor choice",
      "Stage-release funding available for larger projects",
      "Decision within 48 hours",
      "Fixed monthly payments throughout the term",
      "No early repayment penalty",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Property owner within the EU",
      "Minimum net monthly income of €1,800",
      "Renovation project located within the EU",
    ],
    faq: [
      {
        q: "What is stage-release funding?",
        a: "For projects over €30,000 we release funds in stages as work completes, so you only pay interest on what has been drawn.",
      },
      {
        q: "Do I have to use an approved contractor?",
        a: "No. Choose any contractor you like; we only ask for a quote or invoice for larger releases.",
      },
      {
        q: "Can renters apply?",
        a: "The loan is for property owners. Renters looking to furnish a home may find the Short Term Loan more suitable.",
      },
    ],
    keywords: [
      "renovation",
      "home improvement",
      "refurbishment",
      "construction",
      "interior",
      "kitchen",
      "bathroom",
      "extension",
      "remodel",
      "home works",
      "DIY",
    ],
    feeSummary: "No arrangement fee · no early repayment penalty",
    regulatoryNote: REGULATORY,
    personas: ["family", "pre_retirement"],
    goals: ["home", "borrow"],
    relatedSkus: ["LOAN-GREEN-001", "INS-HOME-001", "LOAN-REAL-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 4.5,
    minAmount: 5000,
    maxAmount: 100000,
    minTermMonths: 12,
    termMonths: 120,
    riskLevel: 1,
    minAge: 18,
    minIncome: 21600,
    customerRating: 4.6,
    reviewCount: 742,
    popularityScore: 58,
  },
  {
    sku: "LOAN-GREEN-001",
    name: "Green Home Energy Loan",
    navLabel: "Green Energy",
    category: "Loans",
    subcategory: "Green Energy",
    productType: "Green Home Energy Loan",
    url: "/products/loans/green-energy-loan",
    accent: "#15803D",
    badge: "Lowest renovation rate",
    segment: "personal",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "Discounted financing for solar panels, heat pumps, insulation and EV chargers — from 3.5% APR with no arrangement fee.",
    cardDescription:
      "Cut your energy bills and your carbon footprint with discounted financing for solar, heat pumps and insulation.",
    tagline: "Make your home greener — and cheaper to run — at our lowest renovation rate.",
    longDescription:
      "The Green Home Energy Loan finances upgrades that lower your energy bills: solar panels, heat pumps, insulation, triple glazing and home EV chargers. Because these projects reduce your running costs, we price it below our standard renovation loan and add no arrangement fee. Funds are released against installer quotes, and eligible projects can be combined with national energy grants.",
    displayPrice: "from 3.5% APR",
    perks: [
      "Rate 1% below our standard renovation loan",
      "Covers solar, heat pumps, insulation and EV chargers",
      "Combine with national and regional energy grants",
      "Decision within 48 hours",
      "No early repayment penalty",
    ],
    features: [
      "From 3.5% APR — our lowest home improvement rate",
      "Borrow €2,000 to €50,000 over up to 10 years",
      "Funds released against installer quotes",
      "Works alongside national energy-efficiency grants",
      "No arrangement fee and no early repayment penalty",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Property owner within the EU",
      "Minimum net monthly income of €1,500",
      "Quote from a certified installer for the works",
    ],
    faq: [
      {
        q: "Which projects qualify?",
        a: "Solar panels, heat pumps, insulation, glazing, home batteries and EV chargers installed by a certified installer.",
      },
      {
        q: "Can I combine it with a government grant?",
        a: "Yes. Many customers finance the balance after a grant; we can also bridge the grant if it is paid on completion.",
      },
      {
        q: "How is it different from the renovation loan?",
        a: "Same process, lower rate — because the works reduce your energy bills, we price the risk lower.",
      },
    ],
    keywords: [
      "green loan",
      "solar panels",
      "heat pump",
      "insulation",
      "energy efficiency",
      "EV charger",
      "eco renovation",
      "lower energy bills",
      "sustainable home",
      "home battery",
      "double glazing",
    ],
    feeSummary: "No arrangement fee · no early repayment penalty",
    regulatoryNote: REGULATORY,
    personas: ["family", "pre_retirement"],
    goals: ["home", "borrow", "save"],
    relatedSkus: ["LOAN-RENO-001", "INS-HOME-001", "INV-ESG-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 3.5,
    minAmount: 2000,
    maxAmount: 50000,
    minTermMonths: 12,
    termMonths: 120,
    riskLevel: 1,
    minAge: 18,
    minIncome: 18000,
    customerRating: 4.8,
    reviewCount: 188,
    popularityScore: 55,
  },
  {
    sku: "LOAN-CONS-001",
    name: "Debt Consolidation Loan",
    navLabel: "Debt Consolidation",
    category: "Loans",
    subcategory: "Consolidation",
    productType: "Debt Consolidation Loan",
    url: "/products/loans/debt-consolidation-loan",
    accent: "#0F766E",
    badge: "One monthly payment",
    segment: "personal",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "Combine credit cards, overdrafts and other loans into one fixed monthly payment from 6.9% APR — with a clear end date.",
    cardDescription:
      "Replace several balances with one fixed monthly payment and a clear payoff date.",
    tagline: "One payment, one rate, one end date — take control of what you owe.",
    longDescription:
      "The Debt Consolidation Loan pays off your existing credit cards, overdrafts and personal loans and replaces them with a single fixed monthly repayment. You know exactly what you pay and when you will be debt-free. We settle the other lenders directly on your behalf, and the app shows your payoff progress month by month.",
    displayPrice: "from 6.9% APR",
    perks: [
      "One fixed payment instead of several",
      "We settle your other lenders directly",
      "Clear payoff date from day one",
      "Borrow €2,500 to €40,000",
      "No early repayment penalty",
    ],
    features: [
      "Consolidate cards, overdrafts and loans into one repayment",
      "Fixed rate and fixed monthly amount for the full term",
      "Direct settlement of existing balances",
      "Payoff tracker and reminders in the app",
      "Optional payment holiday of one month per year",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum net monthly income of €1,500",
      "Existing balances with regulated lenders",
      "No active loan defaults",
    ],
    faq: [
      {
        q: "Will consolidating lower my total cost?",
        a: "Usually, when the new rate is below what you pay on cards and overdrafts. The app shows the comparison before you accept.",
      },
      {
        q: "Do you pay my other lenders?",
        a: "Yes. We transfer the funds directly to them on drawdown so nothing is missed.",
      },
      {
        q: "Can I add a balance later?",
        a: "You can top up the loan once in the first year, subject to affordability.",
      },
    ],
    keywords: [
      "debt consolidation",
      "consolidate debt",
      "refinance",
      "pay off credit cards",
      "one monthly payment",
      "lower interest",
      "overdraft",
      "personal loan",
      "debt free",
      "budgeting",
    ],
    feeSummary: "No arrangement fee · no early repayment penalty",
    regulatoryNote: REGULATORY,
    personas: ["all", "young_professional"],
    goals: ["borrow", "save"],
    relatedSkus: ["SVC-COACH-001", "ACC-EVERY-001", "SAV-INST-001"],
    rateType: "fixed",
    price: 0,
    interestRate: 6.9,
    minAmount: 2500,
    maxAmount: 40000,
    minTermMonths: 12,
    termMonths: 84,
    riskLevel: 1,
    minAge: 18,
    minIncome: 18000,
    customerRating: 4.5,
    reviewCount: 231,
    popularityScore: 48,
  },
]);
