import { defineProducts } from "./types";

const REGULATORY = "Eligibility subject to discovery meeting and source-of-wealth verification.";

export const PRIVATE_BANKING = defineProducts([
  {
    sku: "PB-REL-001",
    name: "Dedicated Relationship Manager",
    navLabel: "Relationship Manager",
    category: "Private Banking",
    subcategory: "Relationship",
    productType: "Private Banking",
    url: "/products/private-banking/relationship-manager",
    accent: "#B45309",
    badge: "Always available",
    segment: "private",
    tier: "private",
    launchedAt: "2023-11-01T00:00:00",
    description:
      "A single named point of contact for every financial need — direct phone, email and in-person access.",
    cardDescription:
      "A single point of contact for every financial need — accessible by phone, email or in person, at any time.",
    tagline: "A single named point of contact for every financial need.",
    longDescription:
      "Your Dedicated Relationship Manager is your single point of contact across the entire NexaBank platform — from day-to-day banking to investments, credit and beyond. Reach them directly by phone, email or in person, with a quarterly review of your portfolio, goals and the wider market.",
    displayPrice: "By appointment",
    specs: [
      { label: "Fee structure", value: "Tiered (0.4–0.8%)" },
      { label: "Commitment", value: "Annual review" },
    ],
    perks: [
      "Single named relationship manager",
      "Direct phone, email and in-person access",
      "Quarterly portfolio and goals review",
      "Coordination across all your NexaBank services",
      "Annual relationship summary and outlook",
    ],
    features: [
      "Single named relationship manager",
      "Direct phone, email and in-person access",
      "Quarterly portfolio and goals review",
      "Coordination across all your NexaBank services",
      "Annual relationship summary and outlook",
    ],
    eligibility: [
      "Minimum €500,000 in assets across NexaBank",
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Reference and source-of-wealth checks completed",
    ],
    faq: [
      {
        q: "What does the tiered fee cover?",
        a: "Between 0.4% and 0.8% of assets under management a year, decreasing as assets grow — it covers advice, execution and reporting.",
      },
      {
        q: "Can I meet my manager in person?",
        a: "Yes, at any NexaBank private office or at your home or workplace by arrangement.",
      },
      {
        q: "What if my manager changes?",
        a: "We guarantee a personal handover meeting and continuity of your full history and preferences.",
      },
    ],
    keywords: [
      "private banking",
      "relationship manager",
      "dedicated",
      "personalised",
      "high net worth",
      "wealth",
      "private banker",
      "personal banker",
      "concierge banking",
      "affluent",
      "portfolio review",
    ],
    feeSummary: "Tiered 0.4–0.8% of assets per year",
    regulatoryNote: REGULATORY,
    personas: ["pre_retirement", "hnw"],
    goals: ["invest", "retire"],
    relatedSkus: ["PB-WLTH-001", "CARD-PRES-001", "INV-FUND-001"],
    price: 0,
    annualFeePct: 0.8,
    minAmount: 500000,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.9,
    reviewCount: 312,
    popularityScore: 44,
  },
  {
    sku: "PB-WLTH-001",
    name: "Wealth Planning",
    navLabel: "Wealth Planning",
    category: "Private Banking",
    subcategory: "Wealth",
    productType: "Wealth Planning",
    url: "/products/private-banking/wealth-planning",
    accent: "#92400E",
    badge: "Multi-generational",
    segment: "private",
    tier: "private",
    launchedAt: "2023-11-01T00:00:00",
    description:
      "Long-term planning across succession, philanthropy and cross-border tax — coordinated by our specialists.",
    cardDescription:
      "Long-term wealth planning covering succession, philanthropy and cross-border tax — handled by our in-house specialists.",
    tagline: "Long-term planning across succession, philanthropy and cross-border tax.",
    longDescription:
      "Wealth Planning addresses the questions that go beyond portfolio returns: how to pass wealth to the next generation, structure a family foundation, optimise tax across multiple jurisdictions, and align finances with personal values. Our in-house specialists work alongside your existing lawyers and accountants.",
    displayPrice: "By appointment",
    specs: [
      { label: "Fee structure", value: "Bespoke" },
      { label: "Commitment", value: "Multi-year mandate" },
    ],
    perks: [
      "Succession and inheritance planning",
      "Cross-border tax optimisation",
      "Philanthropy and family foundation structures",
      "Coordination with external lawyers and accountants",
      "Annual strategy review with senior partners",
    ],
    features: [
      "Succession and inheritance planning",
      "Cross-border tax optimisation",
      "Philanthropy and family foundation structures",
      "Coordination with external lawyers and accountants",
      "Annual strategy review with senior partners",
    ],
    eligibility: [
      "Minimum €2,000,000 in assets across NexaBank",
      "Existing Dedicated Relationship Manager",
      "Reference and source-of-wealth checks completed",
      "Engagement scoped via initial discovery meeting",
    ],
    faq: [
      {
        q: "How is a bespoke fee set?",
        a: "After the discovery meeting we scope the mandate and quote a fixed annual fee based on complexity, not assets.",
      },
      {
        q: "Do you replace my lawyer or accountant?",
        a: "No — we coordinate with them and bring specialist expertise on structuring, tax and philanthropy.",
      },
      {
        q: "Can you help with a family business?",
        a: "Yes — succession, governance and liquidity planning for family-owned businesses are core to the service.",
      },
    ],
    keywords: [
      "wealth management",
      "financial planning",
      "legacy",
      "patrimony",
      "family office",
      "inheritance",
      "succession planning",
      "philanthropy",
      "estate planning",
      "cross-border tax",
      "trust",
    ],
    feeSummary: "Bespoke fixed annual fee",
    regulatoryNote: REGULATORY,
    personas: ["pre_retirement", "hnw"],
    goals: ["retire", "family", "invest"],
    relatedSkus: ["PB-REL-001", "PB-CRED-001", "SVC-RETIRE-001"],
    price: 0,
    minAmount: 2000000,
    riskLevel: 3,
    minAge: 18,
    customerRating: 4.9,
    reviewCount: 96,
    popularityScore: 31,
  },
  {
    sku: "PB-CRED-001",
    name: "Exclusive Credit Line",
    navLabel: "Credit Line",
    category: "Private Banking",
    subcategory: "Credit",
    productType: "Private Credit",
    url: "/products/private-banking/credit-line",
    accent: "#78350F",
    badge: "Up to €10M",
    segment: "private",
    tier: "private",
    launchedAt: "2023-11-01T00:00:00",
    description:
      "Unsecured or asset-backed credit lines up to €10M — priced on relationship, with same-day extension decisions.",
    cardDescription:
      "Unsecured or asset-backed credit facilities up to €10M, priced on relationship, not on tick-box criteria.",
    tagline: "Unsecured or asset-backed credit up to €10M, priced on relationship.",
    longDescription:
      "The Exclusive Credit Line gives Private Banking clients access to credit facilities that don't fit a standard underwriting box. Unsecured or backed by your investment portfolio, real estate or other assets, with pricing reflecting the full relationship rather than a published rate card. Drawdowns can be made in any major currency.",
    displayPrice: "Bespoke pricing",
    specs: [
      { label: "Fee structure", value: "Negotiated" },
      { label: "Commitment", value: "Revolving facility" },
    ],
    perks: [
      "Credit lines up to €10M",
      "Unsecured or asset-backed structures",
      "Pricing based on full client relationship",
      "Drawdown in any major currency",
      "Same-day decision on extension requests",
    ],
    features: [
      "Credit lines up to €10M",
      "Unsecured or asset-backed structures",
      "Pricing based on the full client relationship",
      "Drawdown in any major currency",
      "Same-day decision on extension requests",
    ],
    eligibility: [
      "Minimum €1,000,000 in assets across NexaBank",
      "Existing Dedicated Relationship Manager",
      "Source-of-wealth and credit checks completed",
      "Facility scoped via individual underwriting",
    ],
    faq: [
      {
        q: "What can secure the facility?",
        a: "An investment portfolio held with NexaBank (Lombard lending), real estate, or other verifiable assets — or nothing, for unsecured lines.",
      },
      {
        q: "How is the rate set?",
        a: "Negotiated from 2.5% APR depending on collateral, currency and the overall relationship.",
      },
      {
        q: "Can I draw in US dollars?",
        a: "Yes — drawdowns are available in EUR, USD, GBP, CHF and JPY.",
      },
    ],
    keywords: [
      "private credit",
      "lombard",
      "credit line",
      "collateral",
      "bespoke",
      "revolving credit",
      "portfolio lending",
      "liquidity",
      "large loan",
      "asset-backed",
      "multi-currency",
    ],
    feeSummary: "Negotiated · from 2.5% APR",
    regulatoryNote: REGULATORY,
    personas: ["pre_retirement", "hnw"],
    goals: ["borrow", "invest"],
    relatedSkus: ["PB-REL-001", "PB-WLTH-001", "LOAN-REAL-001"],
    rateType: "variable",
    price: 0,
    interestRate: 2.5,
    minAmount: 1000000,
    maxAmount: 10000000,
    riskLevel: 3,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 58,
    popularityScore: 28,
  },
]);
