import { defineProducts } from "./types";

const DGS = "Deposits protected up to €100,000 per depositor by the EU Deposit Guarantee Scheme.";

export const SAVINGS = defineProducts([
  {
    sku: "SAV-INST-001",
    name: "Instant Access Savings",
    navLabel: "Instant Access",
    category: "Savings",
    subcategory: "Instant Access",
    productType: "Savings Account",
    url: "/products/savings/instant-access",
    accent: "#16A34A",
    badge: "No notice period",
    segment: "personal",
    tier: "standard",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "Earn interest from day one with no restrictions on withdrawals — interest accrues daily and is paid monthly.",
    cardDescription:
      "Earn interest from day one with no restrictions on withdrawals. Your money is always available when you need it.",
    tagline: "Earn interest from day one with no restrictions on withdrawals.",
    longDescription:
      "Instant Access Savings is the simplest way to start earning a competitive rate on cash you want to keep available. There's no minimum opening deposit, no notice period and no penalty for withdrawing — interest accrues daily and is paid monthly straight into your account.",
    displayPrice: "3.5% AER",
    access: "Instant withdrawal",
    perks: [
      "No minimum deposit to open",
      "Withdraw anytime, no penalty",
      "Interest paid monthly",
      "Manage entirely in the app",
      "FSCS protected up to €100,000",
    ],
    features: [
      "No minimum deposit to open the account",
      "Withdraw anytime with no penalty",
      "Interest accrues daily, paid monthly",
      "Manage entirely from the NexaBank app",
      "FSCS-equivalent protection up to €100,000",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account",
      "Valid government-issued ID",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "Is the rate fixed?",
        a: "No — 3.5% AER is variable and can move with market rates. We notify you in the app before any change.",
      },
      {
        q: "How quickly can I withdraw?",
        a: "Instantly, to your NexaBank current account, at any hour.",
      },
      {
        q: "Is my money protected?",
        a: "Yes, up to €100,000 per depositor under the EU Deposit Guarantee Scheme.",
      },
    ],
    keywords: [
      "savings",
      "instant access",
      "flexible",
      "no notice",
      "easy saver",
      "emergency fund",
      "rainy day",
      "safe place for savings",
      "easy access savings",
      "daily interest",
    ],
    feeSummary: "No fees · interest paid monthly",
    regulatoryNote: DGS,
    personas: ["all"],
    goals: ["save"],
    relatedSkus: ["SAV-NOT-001", "SAV-ROUND-001", "ACC-EVERY-001"],
    rateType: "variable",
    liquidity: "instant",
    price: 0,
    aer: 3.5,
    minAmount: 0,
    maxAmount: 250000,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 8120,
    popularityScore: 95,
  },
  {
    sku: "SAV-NOT-001",
    name: "Notice Account",
    navLabel: "Notice Account",
    category: "Savings",
    subcategory: "Notice Account",
    productType: "Savings Account",
    url: "/products/savings/notice-account",
    accent: "#0891B2",
    badge: "Higher rate",
    segment: "personal",
    tier: "standard",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "Commit to a 30 or 90-day notice period and earn a meaningfully higher rate on your savings.",
    cardDescription:
      "Commit to a 30 or 90-day notice period and earn a higher rate. Ideal if you rarely need instant access.",
    tagline: "Commit to a short notice period and earn a higher rate on your savings.",
    longDescription:
      "The Notice Account rewards you for planning your withdrawals ahead. Choose between a 30 or 90-day notice period and earn a meaningfully higher rate than Instant Access. Ideal if you rarely need cash on short notice but want better returns than a standard savings account.",
    displayPrice: "4.1% AER",
    access: "30 or 90-day notice",
    perks: [
      "Choice of 30 or 90-day notice period",
      "Higher rate than instant access",
      "No upper age limit",
      "Interest paid quarterly",
      "FSCS protected up to €100,000",
    ],
    features: [
      "Choice of 30 or 90-day notice period",
      "Higher rate than Instant Access",
      "No upper age limit",
      "Interest paid quarterly",
      "FSCS-equivalent protection up to €100,000",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum opening deposit of €1,000",
      "Active NexaBank current account",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "What happens if I need the money sooner?",
        a: "You can request an early withdrawal; the interest for the notice period you skipped is deducted.",
      },
      {
        q: "Which notice period pays 4.1%?",
        a: "The 90-day option. The 30-day option pays 3.8% AER.",
      },
      {
        q: "Can I add money at any time?",
        a: "Yes, top-ups are unlimited up to the €500,000 balance cap.",
      },
    ],
    keywords: [
      "notice account",
      "30 day",
      "90 day",
      "higher rate",
      "structured savings",
      "planned savings",
      "better rate",
      "medium term savings",
      "house deposit savings",
    ],
    feeSummary: "No fees · interest paid quarterly",
    regulatoryNote: DGS,
    personas: ["family", "pre_retirement"],
    goals: ["save", "home"],
    relatedSkus: ["SAV-TERM-001", "SAV-INST-001", "LOAN-REAL-001"],
    rateType: "variable",
    liquidity: "notice",
    price: 0,
    aer: 4.1,
    minAmount: 1000,
    maxAmount: 500000,
    noticeDays: 90,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.6,
    reviewCount: 2310,
    popularityScore: 72,
  },
  {
    sku: "SAV-TERM-001",
    name: "Term Deposit",
    navLabel: "Term Deposit",
    category: "Savings",
    subcategory: "Term Deposit",
    productType: "Term Deposit",
    url: "/products/savings/term-deposit",
    accent: "#2563FF",
    badge: "Guaranteed return",
    segment: "personal",
    tier: "standard",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "Lock in a guaranteed rate for 6, 12 or 24 months — no market risk on your capital during the term.",
    cardDescription:
      "Lock in a guaranteed rate for 6, 12 or 24 months. No market risk — ideal for medium-term goals.",
    tagline: "Lock in a guaranteed rate for 6, 12 or 24 months — no market risk.",
    longDescription:
      "A Term Deposit is the right choice when you have a known time horizon and want a guaranteed return. Lock in a fixed rate at the moment you open the account; your interest is paid at maturity and the rate is unaffected by market movements during the term. Choose 6, 12 or 24 months.",
    displayPrice: "up to 4.8% AER",
    access: "Fixed term (6–24 months)",
    perks: [
      "Fixed rate locked in at opening",
      "Choose 6, 12 or 24-month term",
      "Interest paid at maturity",
      "Auto-renewal option available",
      "FSCS protected up to €100,000",
    ],
    features: [
      "Fixed rate locked in at the moment of opening",
      "Choice of 6, 12 or 24-month term",
      "Interest paid at maturity",
      "Optional auto-renewal at the prevailing rate",
      "FSCS-equivalent protection up to €100,000",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Minimum opening deposit of €1,000",
      "Active NexaBank current account",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "Which term pays 4.8%?",
        a: "The 24-month term. 12 months pays 4.5% and 6 months pays 4.2% AER.",
      },
      {
        q: "Can I break the deposit early?",
        a: "Only in exceptional circumstances, and the interest earned is reduced. Choose a Notice Account if you may need access.",
      },
      {
        q: "What happens at maturity?",
        a: "Funds and interest return to your current account, or roll into a new term if you enabled auto-renewal.",
      },
    ],
    keywords: [
      "term deposit",
      "fixed rate",
      "bond",
      "lock in",
      "guaranteed return",
      "fixed savings",
      "no risk",
      "certificate of deposit",
      "12 month savings",
      "24 month savings",
      "safe return",
    ],
    feeSummary: "No fees · interest paid at maturity",
    regulatoryNote: DGS,
    personas: ["pre_retirement", "family"],
    goals: ["save"],
    relatedSkus: ["SAV-NOT-001", "INV-BOND-001", "SAV-INST-001"],
    rateType: "fixed",
    liquidity: "term",
    price: 0,
    aer: 4.8,
    minAmount: 1000,
    maxAmount: 1000000,
    minTermMonths: 6,
    termMonths: 24,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 1980,
    popularityScore: 68,
  },
  {
    sku: "SAV-REG-001",
    name: "Regulated Savings Account",
    navLabel: "Regulated",
    category: "Savings",
    subcategory: "Regulated",
    productType: "Savings Account",
    url: "/products/savings/regulated-savings",
    accent: "#7C3AED",
    badge: "Tax advantages",
    segment: "personal",
    tier: "standard",
    launchedAt: "2022-01-10T00:00:00",
    description:
      "A government-backed regulated account with tax advantages and full capital protection up to €22,950.",
    cardDescription:
      "A government-backed regulated account with tax advantages and full capital protection. Max €22,950.",
    tagline: "A government-backed regulated account with tax advantages and full capital protection.",
    longDescription:
      "Regulated Savings combines instant access with the tax efficiency of a government-backed scheme. Interest is exempt from income tax up to the regulatory cap, capital is fully protected, and the minimum opening deposit is just €10 — making it the most accessible tax-advantaged account in our range.",
    displayPrice: "3.0% AER",
    access: "Instant withdrawal",
    specs: [{ label: "Max. deposit", value: "Max €22,950" }],
    perks: [
      "Interest exempt from income tax",
      "Government-backed capital protection",
      "Minimum opening deposit of just €10",
      "No account management fees",
      "Regulated by national authority",
    ],
    features: [
      "Interest exempt from income tax (within regulatory limits)",
      "Government-backed capital protection",
      "Minimum opening deposit of just €10",
      "No account management fees",
      "Regulated by the national financial authority",
    ],
    eligibility: [
      "Aged 18 or over and resident in the eligible jurisdiction",
      "Maximum balance capped at €22,950 per holder",
      "Active NexaBank current account",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "Why is the balance capped at €22,950?",
        a: "The cap is set by the regulator for this tax-free scheme. Interest above the cap is not tax-exempt, so we stop deposits there.",
      },
      {
        q: "Can I have one at another bank too?",
        a: "No — one regulated account per person across all banks.",
      },
      {
        q: "Is the interest really tax-free?",
        a: "Yes, interest on this account is exempt from income tax and social charges.",
      },
    ],
    keywords: [
      "regulated",
      "tax free",
      "government backed",
      "secure",
      "capital guaranteed",
      "tax-free savings",
      "livret",
      "state guaranteed",
      "safe savings",
      "zero risk",
    ],
    feeSummary: "No fees · interest tax-exempt",
    regulatoryNote: "Government-backed scheme; balance capped at €22,950 per holder. " + DGS,
    personas: ["all", "student"],
    goals: ["save"],
    relatedSkus: ["SAV-INST-001", "SAV-JUN-001", "ACC-EVERY-001"],
    rateType: "variable",
    liquidity: "instant",
    price: 0,
    aer: 3,
    minAmount: 10,
    maxAmount: 22950,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 4460,
    popularityScore: 88,
  },
  {
    sku: "SAV-PEN-001",
    name: "Pension Savings Plan",
    navLabel: "Pension Plan",
    category: "Savings",
    subcategory: "Pension",
    productType: "Pension Plan",
    url: "/products/savings/pension-savings",
    accent: "#B45309",
    badge: "Tax relief",
    segment: "personal",
    tier: "standard",
    launchedAt: "2022-06-01T00:00:00",
    description:
      "Build your retirement pot with tax relief on contributions and a choice of growth or income fund.",
    cardDescription:
      "Build your retirement pot with tax relief on contributions and a range of low-cost investment options.",
    tagline: "Build your retirement pot with tax relief and a range of low-cost funds.",
    longDescription:
      "The Pension Savings Plan is a long-term wrapper for retirement. Contributions qualify for tax relief up to the annual limit, employer matching is supported, and you can consolidate existing pension pots from previous providers. Pick a growth fund or a steady income fund — switch any time inside the app.",
    displayPrice: "from 3.5% AER",
    access: "Retirement age",
    contributionPeriod: "month",
    specs: [{ label: "Rate", value: "from 3.5% AER" }],
    perks: [
      "Tax relief on contributions up to annual limit",
      "Choice of growth or income fund",
      "Employer contribution matching available",
      "Consolidate existing pension pots",
      "Online pension tracker in the app",
    ],
    features: [
      "Tax relief on contributions up to annual limit",
      "Choice of growth or income fund",
      "Employer contribution matching supported",
      "Consolidate pension pots from previous providers",
      "Online pension tracker and projection tool in the app",
    ],
    eligibility: [
      "Aged 18 or over and resident in the eligible jurisdiction",
      "Active NexaBank current account",
      "Minimum monthly contribution of €50",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "When can I access the money?",
        a: "From the legal retirement age, as a lump sum, an annuity or a mix. Early access is allowed for buying a first home.",
      },
      {
        q: "How much tax relief do I get?",
        a: "Contributions are deducted from taxable income up to the annual ceiling — for most people 10% of earnings.",
      },
      {
        q: "Can I transfer an old pension in?",
        a: "Yes. Start the transfer in the app and we handle the paperwork with your previous provider.",
      },
    ],
    keywords: [
      "pension",
      "retirement savings",
      "long term",
      "tax relief",
      "employer contribution",
      "retire",
      "retirement plan",
      "PER",
      "pension pot",
      "save for retirement",
      "old age",
    ],
    feeSummary: "No entry fee · 0.5% annual management fee",
    regulatoryNote: "Funds are locked until retirement age except in cases permitted by law. " + DGS,
    personas: ["pre_retirement", "young_professional"],
    goals: ["retire", "save"],
    relatedSkus: ["INV-PEN-001", "SVC-RETIRE-001", "INV-BOND-001"],
    rateType: "variable",
    liquidity: "retirement",
    price: 0,
    aer: 3.5,
    annualFeePct: 0.5,
    minAmount: 50,
    maxAmount: 0,
    riskLevel: 2,
    minAge: 18,
    customerRating: 4.5,
    reviewCount: 1120,
    popularityScore: 57,
  },
  {
    sku: "SAV-JUN-001",
    name: "Junior Savings Account",
    navLabel: "Junior Savings",
    category: "Savings",
    subcategory: "Junior",
    productType: "Savings Account",
    url: "/products/savings/junior-savings",
    accent: "#0D9488",
    badge: "For under-18s",
    segment: "kids",
    tier: "standard",
    launchedAt: "2026-08-01T00:00:00",
    description:
      "A 4.0% AER savings account for children under 18, managed by a parent — gifts, pocket money and birthday cash grow tax-free.",
    cardDescription:
      "Start saving for your child at 4.0% AER. Parents manage it, kids watch it grow in their own app view.",
    tagline: "Give your child a head start — savings that grow with them.",
    longDescription:
      "The Junior Savings Account lets a parent or guardian save on behalf of a child under 18 at one of our best rates. Deposit gifts, pocket money and birthday cash from as little as €10; the child sees the balance and goals in NexaKids, but only the parent can withdraw. Interest is tax-free within the child's allowance and the account converts to an adult savings account at 18.",
    displayPrice: "4.0% AER",
    access: "Parent-managed, instant withdrawal",
    perks: [
      "4.0% AER — one of our best rates",
      "Open in the child's name from €10",
      "Parent controls deposits and withdrawals",
      "Child sees savings goals in NexaKids",
      "Converts to an adult account at 18",
    ],
    features: [
      "Competitive 4.0% AER variable rate",
      "Held in the child's name, managed by a parent or guardian",
      "Family and friends can contribute with a gift link",
      "Savings goals with progress the child can follow",
      "Automatic conversion to Instant Access Savings at 18",
    ],
    eligibility: [
      "Child aged 0 to 17",
      "Parent or legal guardian holds an active NexaBank current account",
      "Child's identity document provided at opening",
      "One Junior Savings Account per child",
    ],
    faq: [
      {
        q: "Who can withdraw the money?",
        a: "Only the parent or guardian who opened the account, until the child turns 18 and takes it over.",
      },
      {
        q: "Can grandparents pay in?",
        a: "Yes — share the gift link and anyone can contribute directly.",
      },
      {
        q: "Is the interest taxed?",
        a: "Interest is tax-free within the child's personal allowance.",
      },
    ],
    keywords: [
      "junior savings",
      "kids savings",
      "children savings account",
      "save for my child",
      "pocket money",
      "birthday money",
      "grandchild",
      "under 18",
      "education fund",
      "child account",
    ],
    feeSummary: "No fees · interest paid monthly",
    regulatoryNote: DGS,
    personas: ["kids_teens", "family"],
    goals: ["kids", "save", "family"],
    relatedSkus: ["ACC-KIDS-001", "INV-JUN-001", "ACC-JOINT-001"],
    rateType: "variable",
    liquidity: "instant",
    price: 0,
    aer: 4,
    minAmount: 10,
    maxAmount: 50000,
    riskLevel: 1,
    minAge: 0,
    customerRating: 4.9,
    reviewCount: 214,
    popularityScore: 52,
  },
  {
    sku: "SAV-ROUND-001",
    name: "Round-Up Savings Pots",
    navLabel: "Round-Up Pots",
    category: "Savings",
    subcategory: "Goal Pots",
    productType: "Savings Account",
    url: "/products/savings/round-up-pots",
    accent: "#059669",
    badge: "Saves automatically",
    segment: "personal",
    tier: "standard",
    launchedAt: "2026-08-01T00:00:00",
    description:
      "Goal-based savings pots that round up every card payment to the nearest euro and sweep the change into savings at 3.5% AER.",
    cardDescription:
      "Round up every card payment to the nearest euro and watch the spare change build towards your goals.",
    tagline: "Save without thinking — every purchase tops up your goals.",
    longDescription:
      "Round-Up Savings Pots turn everyday spending into effortless saving. Every card payment is rounded up to the nearest euro and the difference lands in a pot of your choice — a holiday, a deposit, a new phone. Add a multiplier to round up 2× or 5×, set a target and a date, and earn 3.5% AER on everything in the pot. Withdraw instantly whenever you need it.",
    displayPrice: "3.5% AER",
    access: "Instant withdrawal",
    perks: [
      "Round up every card payment automatically",
      "Unlimited named pots with targets",
      "2× and 5× round-up multipliers",
      "3.5% AER on every pot",
      "Withdraw instantly, no penalty",
    ],
    features: [
      "Automatic round-ups on debit and credit card payments",
      "Create pots for any goal with a target amount and date",
      "Multiplier lets you round up 2× or 5× when you want to save faster",
      "Scheduled top-ups on payday",
      "3.5% AER variable interest on all pots",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Active NexaBank current account with a NexaBank card",
      "Valid government-issued ID",
      "Tax residency declared at account opening",
    ],
    faq: [
      {
        q: "How much will I save?",
        a: "The average customer saves €38 a month from round-ups alone, before any scheduled top-ups.",
      },
      {
        q: "Can I pause round-ups?",
        a: "Yes — pause or resume any time in the app, per pot or for all pots.",
      },
      {
        q: "Does it work with my credit card?",
        a: "Yes. Round-ups from NexaBank credit cards are taken from your current account.",
      },
    ],
    keywords: [
      "round up",
      "savings pots",
      "save automatically",
      "spare change",
      "savings goal",
      "holiday fund",
      "save for a deposit",
      "micro saving",
      "budget",
      "first savings",
    ],
    feeSummary: "No fees · interest paid monthly",
    regulatoryNote: DGS,
    personas: ["young_professional", "student"],
    goals: ["save", "travel", "spend"],
    relatedSkus: ["ACC-EVERY-001", "SAV-INST-001", "CARD-START-001"],
    rateType: "variable",
    liquidity: "instant",
    price: 0,
    aer: 3.5,
    minAmount: 0,
    maxAmount: 100000,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 356,
    popularityScore: 66,
  },
]);
