import { defineProducts } from "./types";

const ADVICE = "Sessions provide general guidance and are not personal financial advice unless stated in writing.";

export const SERVICES = defineProducts([
  {
    sku: "SVC-COACH-001",
    name: "Financial Coaching Session",
    navLabel: "Financial Coaching",
    category: "Services",
    subcategory: "Coaching",
    productType: "Advisory Service",
    url: "/products/services/financial-coaching",
    accent: "#64748B",
    badge: "Free for customers",
    segment: "personal",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free 45-minute video session with a NexaBank money coach to review your budget, debts and savings and leave with a written plan.",
    cardDescription:
      "Forty-five minutes with a money coach — budget, debts, savings and a plan you can actually follow. Free.",
    tagline: "A clear plan for your money in 45 minutes — on us.",
    longDescription:
      "The Financial Coaching Session pairs you with a NexaBank money coach for a 45-minute video call. Using your real account data (with your permission), the coach reviews spending, debts and savings, helps you set two or three realistic goals, and sends a written plan afterwards. It is free for customers, with an optional follow-up session after three months to check progress.",
    displayPrice: "Free",
    access: "Book a slot in the app, evenings and weekends available",
    specs: [
      { label: "Length", value: "45 minutes, video" },
      { label: "Availability", value: "Evenings & weekends" },
      { label: "Fee", value: "Free for customers" },
    ],
    perks: [
      "45-minute video session",
      "Written plan sent afterwards",
      "Evening and weekend slots",
      "Optional 3-month follow-up",
      "Free for NexaBank customers",
    ],
    features: [
      "Review of spending, debts and savings using your real data",
      "Two or three prioritised goals with concrete next steps",
      "Written summary and plan within 24 hours",
      "Follow-up session after three months",
      "Available in English, French, Dutch, German and Spanish",
    ],
    eligibility: [
      "Aged 18 or over",
      "Active NexaBank current account",
      "Consent to share account data with the coach for the session",
      "One session per customer every six months",
    ],
    faq: [
      {
        q: "Is this financial advice?",
        a: "It is coaching on budgeting and habits. Product recommendations are general guidance unless a regulated adviser confirms them in writing.",
      },
      {
        q: "Do I have to share my accounts?",
        a: "Sharing is optional but makes the session far more useful; access is revoked automatically afterwards.",
      },
      {
        q: "How do I book?",
        a: "In the app under Support → Money coaching. Most slots are available within a week.",
      },
    ],
    keywords: [
      "financial coaching",
      "money coach",
      "budgeting help",
      "debt advice",
      "financial planning",
      "savings plan",
      "money management",
      "get out of debt",
      "financial wellbeing",
      "free advice",
    ],
    feeSummary: "Free · optional follow-up included",
    regulatoryNote: ADVICE,
    personas: ["all", "young_professional"],
    goals: ["save", "borrow", "spend"],
    relatedSkus: ["LOAN-CONS-001", "SAV-ROUND-001", "INV-ROBO-001"],
    price: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.9,
    reviewCount: 540,
    popularityScore: 59,
  },
  {
    sku: "SVC-RETIRE-001",
    name: "Retirement Planning Consultation",
    navLabel: "Retirement Planning",
    category: "Services",
    subcategory: "Retirement",
    productType: "Advisory Service",
    url: "/products/services/retirement-planning",
    accent: "#475569",
    badge: "Free for customers",
    segment: "personal",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free 60-minute consultation with a qualified retirement adviser to project your pension income and close the gap before you stop working.",
    cardDescription:
      "See what your retirement income really looks like — and what to change while there is still time.",
    tagline: "Know your number, then close the gap — with a qualified retirement adviser.",
    longDescription:
      "The Retirement Planning Consultation is a 60-minute session with a qualified adviser who consolidates your pensions, savings and expected state entitlement into one projection of income at retirement. You leave knowing the gap between what you will have and what you want, with a concrete contribution and product plan to close it. Free for customers; a regulated advice report is available for €149.",
    displayPrice: "Free",
    access: "Book a slot in the app or at a branch",
    specs: [
      { label: "Length", value: "60 minutes, video or in person" },
      { label: "Adviser", value: "Qualified retirement adviser" },
      { label: "Fee", value: "Free · advice report €149" },
    ],
    perks: [
      "60-minute session with a qualified adviser",
      "Projection of your income at retirement",
      "Consolidation review of old pensions",
      "Contribution plan to close the gap",
      "Free for NexaBank customers",
    ],
    features: [
      "Single projection combining pensions, savings and state entitlement",
      "Scenario modelling — retire earlier, contribute more, take less risk",
      "Review of old pensions and whether to transfer them",
      "Written summary of recommended contributions and products",
      "Optional regulated advice report for €149",
    ],
    eligibility: [
      "Aged 18 or over",
      "Active NexaBank current account",
      "Pension statements or provider details to hand",
      "One consultation per customer per year",
    ],
    faq: [
      {
        q: "Is the session regulated advice?",
        a: "The consultation is guidance. If you want personal regulated advice, the adviser prepares a formal report for €149.",
      },
      {
        q: "I'm in my thirties — is it too early?",
        a: "The earlier the better: a small increase in contributions now has the biggest effect on income at 65.",
      },
      {
        q: "Can you consolidate my old pensions?",
        a: "The adviser reviews them; transfers can be started in the app afterwards if they are in your interest.",
      },
    ],
    keywords: [
      "retirement planning",
      "pension advice",
      "retirement income",
      "pension projection",
      "retire early",
      "pension consolidation",
      "how much do I need to retire",
      "pension gap",
      "state pension",
      "retirement adviser",
    ],
    feeSummary: "Free · regulated advice report €149",
    regulatoryNote: ADVICE,
    personas: ["pre_retirement"],
    goals: ["retire", "invest"],
    relatedSkus: ["SAV-PEN-001", "INV-PEN-001", "INV-BOND-001"],
    price: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.9,
    reviewCount: 312,
    popularityScore: 51,
  },
  {
    sku: "SVC-MORT-001",
    name: "Mortgage Advice Appointment",
    navLabel: "Mortgage Advice",
    category: "Services",
    subcategory: "Mortgage",
    productType: "Advisory Service",
    url: "/products/services/mortgage-advice",
    accent: "#334155",
    badge: "Agreement in principle",
    segment: "personal",
    launchedAt: "2026-07-01T00:00:00",
    description:
      "A free appointment with a mortgage advisor to find out how much you can borrow, compare fixed and variable options and get an agreement in principle.",
    cardDescription:
      "Find out what you can borrow and leave with an agreement in principle — free, in person or on video.",
    tagline: "From 'can we afford it?' to an agreement in principle in one appointment.",
    longDescription:
      "The Mortgage Advice Appointment is a free session with a NexaBank mortgage advisor, on video or in a branch. The advisor checks affordability from your income and outgoings, compares fixed and variable Real Estate Loan options, explains the costs beyond the loan — notary, tax, insurance — and issues an agreement in principle you can show estate agents. First-time buyers get a step-by-step guide to the whole purchase.",
    displayPrice: "Free",
    access: "Book a slot in the app or at a branch",
    specs: [
      { label: "Length", value: "60 minutes, video or in branch" },
      { label: "Outcome", value: "Agreement in principle" },
      { label: "Fee", value: "Free" },
    ],
    perks: [
      "Affordability check on your real numbers",
      "Fixed vs. variable comparison",
      "Agreement in principle the same day",
      "First-time buyer walkthrough",
      "Free, no obligation",
    ],
    features: [
      "Affordability assessment and maximum borrowing figure",
      "Comparison of fixed and variable Real Estate Loan options",
      "Full cost breakdown including notary fees, taxes and insurance",
      "Same-day agreement in principle valid for 90 days",
      "Dedicated advisor through to completion if you proceed",
    ],
    eligibility: [
      "Aged 18 or over and EU resident",
      "Buying or remortgaging a property in the EU",
      "Proof of income available for the appointment",
      "No obligation to proceed",
    ],
    faq: [
      {
        q: "What is an agreement in principle?",
        a: "A written indication of how much we would lend you, valid for 90 days, that estate agents accept as proof you are a serious buyer.",
      },
      {
        q: "Do I need to have found a property?",
        a: "No — most people book before they start viewing, to know their budget.",
      },
      {
        q: "Is the appointment free even if I borrow elsewhere?",
        a: "Yes. There is no fee and no obligation.",
      },
    ],
    keywords: [
      "mortgage advice",
      "mortgage advisor",
      "how much can I borrow",
      "first-time buyer",
      "agreement in principle",
      "buying a house",
      "remortgage",
      "home buying help",
      "affordability",
      "property purchase",
    ],
    feeSummary: "Free · no obligation",
    regulatoryNote: ADVICE,
    personas: ["family", "young_professional"],
    goals: ["home", "borrow"],
    relatedSkus: ["LOAN-REAL-001", "INS-HOME-001", "INS-LIFE-001"],
    price: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.8,
    reviewCount: 428,
    popularityScore: 57,
  },
  {
    sku: "SVC-FX-001",
    name: "Currency Exchange & Travel Money",
    navLabel: "Currency Exchange",
    category: "Services",
    subcategory: "Currency",
    productType: "FX Service",
    url: "/products/services/currency-exchange",
    accent: "#0369A1",
    badge: "0% markup on weekdays",
    segment: "personal",
    launchedAt: "2026-07-15T00:00:00",
    description:
      "Exchange 30+ currencies in the app at the mid-market rate with 0% markup on weekdays, hold them in currency wallets and spend with your card abroad.",
    cardDescription:
      "Swap euros for 30+ currencies at the real rate — 0% markup on weekdays — and spend them straight from your card.",
    tagline: "The real exchange rate, in your pocket, before you even leave.",
    longDescription:
      "Currency Exchange & Travel Money lets you convert euros into 30+ currencies inside the app at the mid-market rate with 0% markup Monday to Friday (0.5% at weekends, when markets are closed). Hold the money in currency wallets, spend it directly with your NexaBank card abroad, set alerts for the rate you want, and order cash for collection at partner locations. Everything you exchange is visible in one place with the rate you got.",
    displayPrice: "0% markup on weekdays",
    access: "Instant in the app; cash collection within 24 hours",
    specs: [
      { label: "Rate", value: "Mid-market, 0% markup weekdays" },
      { label: "Currencies", value: "30+" },
      { label: "Cash", value: "Collect within 24 hours" },
    ],
    perks: [
      "Mid-market rate, 0% markup on weekdays",
      "30+ currencies in wallets",
      "Spend wallets directly with your card",
      "Rate alerts",
      "Cash collection at partner locations",
    ],
    features: [
      "Exchange at the mid-market rate with 0% markup Monday to Friday",
      "Hold 30+ currencies in wallets alongside your euro balance",
      "Card payments abroad draw from the matching wallet automatically",
      "Rate alerts and scheduled exchanges",
      "Cash ordering for collection within 24 hours",
    ],
    eligibility: [
      "Aged 18 or over",
      "Active NexaBank current account",
      "Valid government-issued ID",
      "Fair-use limit of €10,000 per month at 0% markup",
    ],
    faq: [
      {
        q: "Why is the weekend rate different?",
        a: "Currency markets close at weekends; a 0.5% markup covers the rate movement until Monday.",
      },
      {
        q: "Is there a limit?",
        a: "€10,000 per month at 0% markup; above that a 0.5% markup applies.",
      },
      {
        q: "Can I get physical cash?",
        a: "Yes — order in the app and collect at a partner location within 24 hours.",
      },
    ],
    keywords: [
      "currency exchange",
      "travel money",
      "foreign currency",
      "exchange rate",
      "holiday money",
      "dollars",
      "pounds",
      "currency wallet",
      "no FX fees",
      "money abroad",
      "cash for travel",
    ],
    feeSummary: "0% markup weekdays · 0.5% weekends and above €10,000/month",
    regulatoryNote: "Exchange rates are live and can move between quote and execution.",
    personas: ["young_professional", "family"],
    goals: ["travel", "spend"],
    relatedSkus: ["CARD-NOM-001", "INS-TRAV-001", "ACC-EVERY-001"],
    liquidity: "instant",
    price: 0,
    fxFeePct: 0,
    riskLevel: 1,
    minAge: 18,
    customerRating: 4.7,
    reviewCount: 1860,
    popularityScore: 71,
  },
]);
