// Product catalog — transcribed from nexabank_product_feed.csv (31 SKUs).
// The SKU values here must stay an exact match to the feed, since DY events
// (productId, slots) are keyed on them.

export type ProductCategory =
  | "Loans"
  | "Cards"
  | "Savings"
  | "Investments"
  | "Insurance"
  | "Crypto"
  | "Cashback"
  | "Private Banking";

export interface Product {
  sku: string;
  name: string;
  category: ProductCategory;
  subcategory: string;
  url: string;
  description: string;
  displayPrice: string;
  lifeStage: string;
  productType: string;
  annualFee: number;
  cashbackPercent: number;
  interestRate: number;
  maxAmount: number;
  minAmount: number;
  riskLevel: number;
  termMonths: number;
}

export const CATEGORY_ACCENT: Record<ProductCategory, string> = {
  Cards: "#0891B2",
  Loans: "#2563FF",
  Savings: "#16A34A",
  Investments: "#7C3AED",
  Insurance: "#EA580C",
  Crypto: "#F59E0B",
  Cashback: "#EC4899",
  "Private Banking": "#B45309",
};

export const PRODUCTS: Product[] = [
  {
    sku: "LOAN-REAL-001",
    name: "Real Estate Loan",
    category: "Loans",
    subcategory: "Real Estate",
    url: "/products/loans/real-estate-loan",
    description:
      "Your home journey starts here — competitive rates and long-term flexibility with terms up to 30 years.",
    displayPrice: "from 3.9% APR",
    lifeStage: "family",
    productType: "Real Estate Loan",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 3.9,
    maxAmount: 1000000,
    minAmount: 50000,
    riskLevel: 1,
    termMonths: 360,
  },
  {
    sku: "LOAN-VEH-001",
    name: "Vehicle Financing",
    category: "Loans",
    subcategory: "Vehicle",
    url: "/products/loans/car-loan",
    description:
      "Drive away sooner with flexible financing for new and used cars up to €75,000.",
    displayPrice: "from 5.5% APR",
    lifeStage: "young_professional",
    productType: "Vehicle Financing",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 5.5,
    maxAmount: 75000,
    minAmount: 3000,
    riskLevel: 1,
    termMonths: 72,
  },
  {
    sku: "LOAN-SHORT-001",
    name: "Short Term Loan",
    category: "Loans",
    subcategory: "Short Term",
    url: "/products/loans/short-term-loan",
    description:
      "Fast funds when you need them — in your account within 24 hours of approval.",
    displayPrice: "from 8.9% APR",
    lifeStage: "all",
    productType: "Short Term Loan",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 8.9,
    maxAmount: 10000,
    minAmount: 500,
    riskLevel: 2,
    termMonths: 24,
  },
  {
    sku: "LOAN-STU-001",
    name: "Student Loan",
    category: "Loans",
    subcategory: "Student",
    url: "/products/loans/student-loan",
    description:
      "Invest in your education — our lowest rate at 2.9% APR with deferred repayment until after graduation.",
    displayPrice: "from 2.9% APR",
    lifeStage: "student",
    productType: "Student Loan",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 2.9,
    maxAmount: 25000,
    minAmount: 1000,
    riskLevel: 1,
    termMonths: 120,
  },
  {
    sku: "LOAN-RENO-001",
    name: "House Renovation Loan",
    category: "Loans",
    subcategory: "Home Improvement",
    url: "/products/loans/renovation-loan",
    description:
      "Transform your home — from a kitchen remodel to a full refurbishment with stage-release funding.",
    displayPrice: "from 4.5% APR",
    lifeStage: "family",
    productType: "House Renovation Loan",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 4.5,
    maxAmount: 100000,
    minAmount: 5000,
    riskLevel: 1,
    termMonths: 120,
  },
  {
    sku: "CARD-START-001",
    name: "NexaStart Card",
    category: "Cards",
    subcategory: "Free",
    url: "/products/credit-cards/nexa-start",
    description:
      "Start your credit journey with no annual fee and 1% cashback on every purchase from day one.",
    displayPrice: "€0/year",
    lifeStage: "student",
    productType: "Credit Card",
    annualFee: 0,
    cashbackPercent: 1,
    interestRate: 0,
    maxAmount: 3000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "CARD-ESS-001",
    name: "NexaEssential Card",
    category: "Cards",
    subcategory: "Essential",
    url: "/products/credit-cards/nexa-essential",
    description:
      "Everyday versatility with basic travel cover and purchase protection up to €1,000 per item.",
    displayPrice: "€49/year",
    lifeStage: "all",
    productType: "Credit Card",
    annualFee: 49,
    cashbackPercent: 0.5,
    interestRate: 19.9,
    maxAmount: 10000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "CARD-NOM-001",
    name: "NexaNomad Card",
    category: "Cards",
    subcategory: "Travel",
    url: "/products/credit-cards/nexa-nomad",
    description:
      "Made for travellers — no FX fees worldwide and two complimentary airport lounge visits per year.",
    displayPrice: "€99/year",
    lifeStage: "young_professional",
    productType: "Credit Card",
    annualFee: 99,
    cashbackPercent: 1.5,
    interestRate: 17.9,
    maxAmount: 20000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "CARD-PRES-001",
    name: "NexaPrestige Card",
    category: "Cards",
    subcategory: "Premium",
    url: "/products/credit-cards/nexa-prestige",
    description:
      "Our most exclusive card — 24/7 concierge service and our highest cashback rate at 2%.",
    displayPrice: "€299/year",
    lifeStage: "pre_retirement",
    productType: "Credit Card",
    annualFee: 299,
    cashbackPercent: 2,
    interestRate: 14.9,
    maxAmount: 100000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "SAV-INST-001",
    name: "Instant Access Savings",
    category: "Savings",
    subcategory: "Instant Access",
    url: "/products/savings/instant-access",
    description:
      "Earn interest from day one with no restrictions on withdrawals — interest accrues daily and is paid monthly.",
    displayPrice: "3.5% AER",
    lifeStage: "all",
    productType: "Savings Account",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 3.5,
    maxAmount: 250000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "SAV-NOT-001",
    name: "Notice Account",
    category: "Savings",
    subcategory: "Notice Account",
    url: "/products/savings/notice-account",
    description:
      "Commit to a 30 or 90-day notice period and earn a meaningfully higher rate on your savings.",
    displayPrice: "4.1% AER",
    lifeStage: "family",
    productType: "Savings Account",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 4.1,
    maxAmount: 500000,
    minAmount: 1000,
    riskLevel: 1,
    termMonths: 90,
  },
  {
    sku: "SAV-TERM-001",
    name: "Term Deposit",
    category: "Savings",
    subcategory: "Term Deposit",
    url: "/products/savings/term-deposit",
    description:
      "Lock in a guaranteed rate for 6, 12 or 24 months — no market risk on your capital during the term.",
    displayPrice: "up to 4.8% AER",
    lifeStage: "pre_retirement",
    productType: "Term Deposit",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 4.8,
    maxAmount: 1000000,
    minAmount: 1000,
    riskLevel: 1,
    termMonths: 12,
  },
  {
    sku: "SAV-REG-001",
    name: "Regulated Savings Account",
    category: "Savings",
    subcategory: "Regulated",
    url: "/products/savings/regulated-savings",
    description:
      "A government-backed regulated account with tax advantages and full capital protection up to €22,950.",
    displayPrice: "3.0% AER",
    lifeStage: "all",
    productType: "Savings Account",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 3,
    maxAmount: 22950,
    minAmount: 10,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "SAV-PEN-001",
    name: "Pension Savings Plan",
    category: "Savings",
    subcategory: "Pension",
    url: "/products/savings/pension-savings",
    description:
      "Build your retirement pot with tax relief on contributions and a choice of growth or income fund.",
    displayPrice: "from 3.5% AER",
    lifeStage: "pre_retirement",
    productType: "Pension Plan",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 3.5,
    maxAmount: 0,
    minAmount: 50,
    riskLevel: 2,
    termMonths: 0,
  },
  {
    sku: "INV-FUND-001",
    name: "Managed Funds",
    category: "Investments",
    subcategory: "Funds",
    url: "/products/investments/managed-funds",
    description:
      "Actively managed portfolios across equities, bonds and alternatives — built and rebalanced by our team.",
    displayPrice: "5–8% p.a. target",
    lifeStage: "family",
    productType: "Investment Fund",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 1000,
    riskLevel: 3,
    termMonths: 0,
  },
  {
    sku: "INV-ETF-001",
    name: "ETFs",
    category: "Investments",
    subcategory: "ETFs",
    url: "/products/investments/etfs",
    description:
      "Trade 500+ global ETFs at a flat €1 commission with fractional shares from €50.",
    displayPrice: "Market-linked",
    lifeStage: "young_professional",
    productType: "ETF",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 50,
    riskLevel: 3,
    termMonths: 0,
  },
  {
    sku: "INV-ROBO-001",
    name: "Robo-Advisory Portfolio",
    category: "Investments",
    subcategory: "Robo",
    url: "/products/investments/robo-advisory",
    description:
      "Tell us your goal — we build a diversified portfolio and rebalance it for you at 0.45% a year.",
    displayPrice: "4–7% p.a. target",
    lifeStage: "young_professional",
    productType: "Robo-Advisory",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 500,
    riskLevel: 3,
    termMonths: 0,
  },
  {
    sku: "INV-PEN-001",
    name: "Investment Pension Plan",
    category: "Investments",
    subcategory: "Pension",
    url: "/products/investments/investment-pension",
    description:
      "A pension wrapper invested in our managed funds with tax relief on contributions up to the annual limit.",
    displayPrice: "5–7% p.a. target",
    lifeStage: "pre_retirement",
    productType: "Investment Pension",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 100,
    riskLevel: 3,
    termMonths: 0,
  },
  {
    sku: "INS-LIFE-001",
    name: "Life Insurance",
    category: "Insurance",
    subcategory: "Life",
    url: "/products/insurance/life-insurance",
    description:
      "A lump-sum payout to your beneficiaries from €50,000 to €1,000,000 of cover with premiums fixed for the term.",
    displayPrice: "from €8/month",
    lifeStage: "family",
    productType: "Life Insurance",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 1000000,
    minAmount: 50000,
    riskLevel: 1,
    termMonths: 360,
  },
  {
    sku: "INS-HOME-001",
    name: "Home Insurance",
    category: "Insurance",
    subcategory: "Home",
    url: "/products/insurance/home-insurance",
    description:
      "Buildings cover up to €1M and contents up to €100,000 — for owners and renters, with 24/7 home assistance.",
    displayPrice: "from €12/month",
    lifeStage: "family",
    productType: "Home Insurance",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 1000000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 12,
  },
  {
    sku: "INS-TRAV-001",
    name: "Travel Insurance",
    category: "Insurance",
    subcategory: "Travel",
    url: "/products/insurance/travel-insurance",
    description:
      "Single-trip or annual multi-trip cover with worldwide medical up to €10M and an optional winter sports add-on.",
    displayPrice: "from €4/trip",
    lifeStage: "young_professional",
    productType: "Travel Insurance",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "INS-INC-001",
    name: "Income Protection",
    category: "Insurance",
    subcategory: "Income",
    url: "/products/insurance/income-protection",
    description:
      "Tax-free monthly payouts replacing up to 70% of your pre-tax income if illness or injury stops you working.",
    displayPrice: "from €15/month",
    lifeStage: "all",
    productType: "Income Protection",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "CRYPTO-BTC-001",
    name: "Bitcoin",
    category: "Crypto",
    subcategory: "Bitcoin",
    url: "/products/crypto/bitcoin",
    description:
      "Buy, sell and hold BTC directly from your NexaBank account with insured cold-storage custody.",
    displayPrice: "0.7% spread",
    lifeStage: "young_professional",
    productType: "Cryptocurrency",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 250000,
    minAmount: 10,
    riskLevel: 5,
    termMonths: 0,
  },
  {
    sku: "CRYPTO-ETH-001",
    name: "Ethereum",
    category: "Crypto",
    subcategory: "Ethereum",
    url: "/products/crypto/ethereum",
    description:
      "Trade ETH and earn staking rewards inside your NexaBank account with insured cold-storage custody.",
    displayPrice: "0.8% spread",
    lifeStage: "young_professional",
    productType: "Cryptocurrency",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 250000,
    minAmount: 10,
    riskLevel: 5,
    termMonths: 0,
  },
  {
    sku: "CRYPTO-PORT-001",
    name: "Crypto Portfolio",
    category: "Crypto",
    subcategory: "Portfolio",
    url: "/products/crypto/crypto-portfolio",
    description:
      "A pre-built basket of the top 10 cryptocurrencies, rebalanced monthly with an all-in 1% annual fee.",
    displayPrice: "1.0% spread",
    lifeStage: "young_professional",
    productType: "Crypto Portfolio",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 1,
    maxAmount: 250000,
    minAmount: 50,
    riskLevel: 5,
    termMonths: 0,
  },
  {
    sku: "CRYPTO-STAK-001",
    name: "Crypto Staking",
    category: "Crypto",
    subcategory: "Staking",
    url: "/products/crypto/crypto-staking",
    description:
      "Earn passive rewards by locking ETH, SOL, ADA and other eligible assets — paid weekly in the staked asset.",
    displayPrice: "Up to 8% APY",
    lifeStage: "young_professional",
    productType: "Crypto Staking",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 8,
    maxAmount: 100000,
    minAmount: 100,
    riskLevel: 5,
    termMonths: 0,
  },
  {
    sku: "CASH-CARD-001",
    name: "Cashback Credit Card",
    category: "Cashback",
    subcategory: "Cards",
    url: "/products/cashback/cashback-card",
    description:
      "Elevated cashback — 3% on groceries and fuel, 1.5% on subscriptions and 1% on everything else.",
    displayPrice: "up to 3% cashback",
    lifeStage: "all",
    productType: "Cashback Card",
    annualFee: 59,
    cashbackPercent: 3,
    interestRate: 19.9,
    maxAmount: 15000,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "CASH-REW-001",
    name: "Cashback Rewards Programme",
    category: "Cashback",
    subcategory: "Rewards",
    url: "/products/cashback/rewards-programme",
    description:
      "Stackable cashback at 300+ partner brands — free for all NexaBank customers and credited within 48 hours.",
    displayPrice: "Free to join",
    lifeStage: "all",
    productType: "Rewards Programme",
    annualFee: 0,
    cashbackPercent: 10,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 0,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "PB-REL-001",
    name: "Dedicated Relationship Manager",
    category: "Private Banking",
    subcategory: "Relationship",
    url: "/products/private-banking/relationship-manager",
    description:
      "A single named point of contact for every financial need — direct phone, email and in-person access.",
    displayPrice: "By appointment",
    lifeStage: "pre_retirement",
    productType: "Private Banking",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 500000,
    riskLevel: 1,
    termMonths: 0,
  },
  {
    sku: "PB-WLTH-001",
    name: "Wealth Planning",
    category: "Private Banking",
    subcategory: "Wealth",
    url: "/products/private-banking/wealth-planning",
    description:
      "Long-term planning across succession, philanthropy and cross-border tax — coordinated by our specialists.",
    displayPrice: "By appointment",
    lifeStage: "pre_retirement",
    productType: "Wealth Planning",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 0,
    maxAmount: 0,
    minAmount: 2000000,
    riskLevel: 2,
    termMonths: 0,
  },
  {
    sku: "PB-CRED-001",
    name: "Exclusive Credit Line",
    category: "Private Banking",
    subcategory: "Credit",
    url: "/products/private-banking/credit-line",
    description:
      "Unsecured or asset-backed credit lines up to €10M — priced on relationship, with same-day extension decisions.",
    displayPrice: "Bespoke pricing",
    lifeStage: "pre_retirement",
    productType: "Private Credit",
    annualFee: 0,
    cashbackPercent: 0,
    interestRate: 2.5,
    maxAmount: 10000000,
    minAmount: 1000000,
    riskLevel: 2,
    termMonths: 0,
  },
];

export function getProduct(sku: string): Product | undefined {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function productsByCategory(category: ProductCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export const CATEGORIES: ProductCategory[] = [
  "Cards",
  "Loans",
  "Savings",
  "Investments",
  "Insurance",
  "Crypto",
  "Cashback",
  "Private Banking",
];

// A representative monetary value for DY events fired against a product
// (Application / Submission / Purchase all need a `value`).
export function eventValue(product: Product): number {
  if (product.minAmount > 0) return product.minAmount;
  if (product.annualFee > 0) return product.annualFee;
  return 100;
}
